#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 103
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 9
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_LT_BANG = 1,
  aux_sym_doctype_token1 = 2,
  anon_sym_GT = 3,
  sym__doctype = 4,
  sym_comment_start_tag = 5,
  anon_sym_LT = 6,
  anon_sym_SLASH_GT = 7,
  sym_comment_end_tag = 8,
  anon_sym_LT_SLASH = 9,
  anon_sym_EQ = 10,
  sym_attribute_name = 11,
  sym_attribute_value = 12,
  anon_sym_SQUOTE = 13,
  aux_sym_quoted_attribute_value_token1 = 14,
  anon_sym_DQUOTE = 15,
  aux_sym_quoted_attribute_value_token2 = 16,
  sym__start_tag_name = 17,
  sym__script_start_tag_name = 18,
  sym__style_start_tag_name = 19,
  sym__end_tag_name = 20,
  sym_erroneous_end_tag_name = 21,
  sym__implicit_end_tag = 22,
  sym_raw_text = 23,
  sym_text = 24,
  sym_fragment = 25,
  sym_doctype = 26,
  sym__node = 27,
  sym_comment = 28,
  sym_element = 29,
  sym_script_element = 30,
  sym_style_element = 31,
  sym_start_tag = 32,
  sym_script_start_tag = 33,
  sym_style_start_tag = 34,
  sym_self_closing_tag = 35,
  sym_end_tag = 36,
  sym_erroneous_end_tag = 37,
  sym_attribute = 38,
  sym_quoted_attribute_value = 39,
  aux_sym_fragment_repeat1 = 40,
  aux_sym_comment_repeat1 = 41,
  aux_sym_start_tag_repeat1 = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG] = "<!",
  [aux_sym_doctype_token1] = "doctype_token1",
  [anon_sym_GT] = ">",
  [sym__doctype] = "doctype",
  [sym_comment_start_tag] = "comment_start_tag",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [sym_comment_end_tag] = "comment_end_tag",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token1] = "attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token2] = "attribute_value",
  [sym__start_tag_name] = "tag_name",
  [sym__script_start_tag_name] = "tag_name",
  [sym__style_start_tag_name] = "tag_name",
  [sym__end_tag_name] = "tag_name",
  [sym_erroneous_end_tag_name] = "erroneous_end_tag_name",
  [sym__implicit_end_tag] = "_implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_text] = "text",
  [sym_fragment] = "fragment",
  [sym_doctype] = "doctype",
  [sym__node] = "_node",
  [sym_comment] = "comment",
  [sym_element] = "element",
  [sym_script_element] = "script_element",
  [sym_style_element] = "style_element",
  [sym_start_tag] = "start_tag",
  [sym_script_start_tag] = "start_tag",
  [sym_style_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_erroneous_end_tag] = "erroneous_end_tag",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [aux_sym_fragment_repeat1] = "fragment_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [aux_sym_doctype_token1] = aux_sym_doctype_token1,
  [anon_sym_GT] = anon_sym_GT,
  [sym__doctype] = sym__doctype,
  [sym_comment_start_tag] = sym_comment_start_tag,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [sym_comment_end_tag] = sym_comment_end_tag,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token1] = sym_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token2] = sym_attribute_value,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__script_start_tag_name] = sym__start_tag_name,
  [sym__style_start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [sym__implicit_end_tag] = sym__implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_text] = sym_text,
  [sym_fragment] = sym_fragment,
  [sym_doctype] = sym_doctype,
  [sym__node] = sym__node,
  [sym_comment] = sym_comment,
  [sym_element] = sym_element,
  [sym_script_element] = sym_script_element,
  [sym_style_element] = sym_style_element,
  [sym_start_tag] = sym_start_tag,
  [sym_script_start_tag] = sym_start_tag,
  [sym_style_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_erroneous_end_tag] = sym_erroneous_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [aux_sym_fragment_repeat1] = aux_sym_fragment_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doctype_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym__doctype] = {
    .visible = true,
    .named = false,
  },
  [sym_comment_start_tag] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_comment_end_tag] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__implicit_end_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '\'') ADVANCE(30);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '<') ADVANCE(23);
      if (lookahead == '=') ADVANCE(27);
      if (lookahead == '>') ADVANCE(20);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '\'') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(29);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(22);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '=') ADVANCE(27);
      if (lookahead == '>') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '<') ADVANCE(28);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(25);
      END_STATE();
    case 9:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 11:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(14);
      END_STATE();
    case 14:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(19);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      if (lookahead == '-') ADVANCE(4);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__doctype);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_comment_start_tag);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(17);
      if (lookahead == '/') ADVANCE(26);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_comment_end_tag);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(35);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 3},
  [3] = {.lex_state = 0, .external_lex_state = 3},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 0, .external_lex_state = 3},
  [13] = {.lex_state = 0, .external_lex_state = 2},
  [14] = {.lex_state = 0, .external_lex_state = 2},
  [15] = {.lex_state = 0, .external_lex_state = 2},
  [16] = {.lex_state = 0, .external_lex_state = 2},
  [17] = {.lex_state = 0, .external_lex_state = 2},
  [18] = {.lex_state = 0, .external_lex_state = 2},
  [19] = {.lex_state = 0, .external_lex_state = 2},
  [20] = {.lex_state = 0, .external_lex_state = 2},
  [21] = {.lex_state = 0, .external_lex_state = 2},
  [22] = {.lex_state = 0, .external_lex_state = 2},
  [23] = {.lex_state = 0, .external_lex_state = 2},
  [24] = {.lex_state = 0, .external_lex_state = 2},
  [25] = {.lex_state = 0, .external_lex_state = 2},
  [26] = {.lex_state = 0, .external_lex_state = 2},
  [27] = {.lex_state = 0, .external_lex_state = 2},
  [28] = {.lex_state = 0, .external_lex_state = 3},
  [29] = {.lex_state = 0, .external_lex_state = 3},
  [30] = {.lex_state = 0, .external_lex_state = 3},
  [31] = {.lex_state = 0, .external_lex_state = 3},
  [32] = {.lex_state = 0, .external_lex_state = 3},
  [33] = {.lex_state = 0, .external_lex_state = 3},
  [34] = {.lex_state = 0, .external_lex_state = 3},
  [35] = {.lex_state = 0, .external_lex_state = 3},
  [36] = {.lex_state = 0, .external_lex_state = 3},
  [37] = {.lex_state = 0, .external_lex_state = 3},
  [38] = {.lex_state = 0, .external_lex_state = 3},
  [39] = {.lex_state = 0, .external_lex_state = 3},
  [40] = {.lex_state = 0, .external_lex_state = 3},
  [41] = {.lex_state = 0, .external_lex_state = 3},
  [42] = {.lex_state = 0, .external_lex_state = 3},
  [43] = {.lex_state = 0, .external_lex_state = 3},
  [44] = {.lex_state = 6, .external_lex_state = 4},
  [45] = {.lex_state = 6, .external_lex_state = 4},
  [46] = {.lex_state = 6, .external_lex_state = 4},
  [47] = {.lex_state = 6, .external_lex_state = 4},
  [48] = {.lex_state = 6, .external_lex_state = 4},
  [49] = {.lex_state = 6},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 6},
  [53] = {.lex_state = 6},
  [54] = {.lex_state = 6},
  [55] = {.lex_state = 6},
  [56] = {.lex_state = 6, .external_lex_state = 4},
  [57] = {.lex_state = 6},
  [58] = {.lex_state = 0, .external_lex_state = 5},
  [59] = {.lex_state = 6, .external_lex_state = 4},
  [60] = {.lex_state = 0, .external_lex_state = 5},
  [61] = {.lex_state = 6, .external_lex_state = 4},
  [62] = {.lex_state = 0, .external_lex_state = 6},
  [63] = {.lex_state = 0, .external_lex_state = 6},
  [64] = {.lex_state = 6, .external_lex_state = 4},
  [65] = {.lex_state = 0, .external_lex_state = 6},
  [66] = {.lex_state = 0, .external_lex_state = 6},
  [67] = {.lex_state = 6},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0, .external_lex_state = 7},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0, .external_lex_state = 7},
  [73] = {.lex_state = 3},
  [74] = {.lex_state = 0, .external_lex_state = 6},
  [75] = {.lex_state = 0, .external_lex_state = 6},
  [76] = {.lex_state = 0, .external_lex_state = 6},
  [77] = {.lex_state = 6},
  [78] = {.lex_state = 6},
  [79] = {.lex_state = 2},
  [80] = {.lex_state = 0, .external_lex_state = 6},
  [81] = {.lex_state = 3},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0, .external_lex_state = 8},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 15},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0, .external_lex_state = 8},
  [99] = {.lex_state = 15},
  [100] = {.lex_state = 0, .external_lex_state = 9},
  [101] = {.lex_state = 0, .external_lex_state = 9},
  [102] = {.lex_state = 0},
};

enum {
  ts_external_token__start_tag_name = 0,
  ts_external_token__script_start_tag_name = 1,
  ts_external_token__style_start_tag_name = 2,
  ts_external_token__end_tag_name = 3,
  ts_external_token_erroneous_end_tag_name = 4,
  ts_external_token_SLASH_GT = 5,
  ts_external_token__implicit_end_tag = 6,
  ts_external_token_raw_text = 7,
  ts_external_token_text = 8,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__script_start_tag_name] = sym__script_start_tag_name,
  [ts_external_token__style_start_tag_name] = sym__style_start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token__implicit_end_tag] = sym__implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_text] = sym_text,
};

static const bool ts_external_scanner_states[10][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_text] = true,
  },
  [2] = {
    [ts_external_token_text] = true,
  },
  [3] = {
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_text] = true,
  },
  [4] = {
    [ts_external_token_SLASH_GT] = true,
  },
  [5] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
  },
  [6] = {
    [ts_external_token_raw_text] = true,
  },
  [7] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
  },
  [8] = {
    [ts_external_token_erroneous_end_tag_name] = true,
  },
  [9] = {
    [ts_external_token__end_tag_name] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym__doctype] = ACTIONS(1),
    [sym_comment_start_tag] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [sym_comment_end_tag] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__script_start_tag_name] = ACTIONS(1),
    [sym__style_start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym_erroneous_end_tag_name] = ACTIONS(1),
    [sym__implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
  },
  [1] = {
    [sym_fragment] = STATE(84),
    [sym_doctype] = STATE(11),
    [sym__node] = STATE(11),
    [sym_comment] = STATE(11),
    [sym_element] = STATE(11),
    [sym_script_element] = STATE(11),
    [sym_style_element] = STATE(11),
    [sym_start_tag] = STATE(5),
    [sym_script_start_tag] = STATE(62),
    [sym_style_start_tag] = STATE(66),
    [sym_self_closing_tag] = STATE(21),
    [sym_erroneous_end_tag] = STATE(11),
    [aux_sym_fragment_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT_BANG] = ACTIONS(5),
    [sym_comment_start_tag] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LT_SLASH] = ACTIONS(11),
    [sym_text] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      sym_comment_start_tag,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      anon_sym_LT_SLASH,
    ACTIONS(23), 1,
      sym__implicit_end_tag,
    ACTIONS(25), 1,
      sym_text,
    STATE(3), 1,
      sym_start_tag,
    STATE(15), 1,
      sym_end_tag,
    STATE(42), 1,
      sym_self_closing_tag,
    STATE(63), 1,
      sym_style_start_tag,
    STATE(65), 1,
      sym_script_start_tag,
    STATE(12), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_comment_repeat1,
  [44] = 12,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      sym_comment_start_tag,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    ACTIONS(29), 1,
      sym__implicit_end_tag,
    ACTIONS(31), 1,
      sym_text,
    STATE(3), 1,
      sym_start_tag,
    STATE(36), 1,
      sym_end_tag,
    STATE(42), 1,
      sym_self_closing_tag,
    STATE(63), 1,
      sym_style_start_tag,
    STATE(65), 1,
      sym_script_start_tag,
    STATE(4), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_comment_repeat1,
  [88] = 12,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      sym_comment_start_tag,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      sym_text,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    ACTIONS(33), 1,
      sym__implicit_end_tag,
    STATE(3), 1,
      sym_start_tag,
    STATE(32), 1,
      sym_end_tag,
    STATE(42), 1,
      sym_self_closing_tag,
    STATE(63), 1,
      sym_style_start_tag,
    STATE(65), 1,
      sym_script_start_tag,
    STATE(12), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_comment_repeat1,
  [132] = 12,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      sym_comment_start_tag,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      anon_sym_LT_SLASH,
    ACTIONS(35), 1,
      sym__implicit_end_tag,
    ACTIONS(37), 1,
      sym_text,
    STATE(3), 1,
      sym_start_tag,
    STATE(19), 1,
      sym_end_tag,
    STATE(42), 1,
      sym_self_closing_tag,
    STATE(63), 1,
      sym_style_start_tag,
    STATE(65), 1,
      sym_script_start_tag,
    STATE(2), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_comment_repeat1,
  [176] = 11,
    ACTIONS(39), 1,
      anon_sym_LT_BANG,
    ACTIONS(42), 1,
      sym_comment_start_tag,
    ACTIONS(45), 1,
      anon_sym_LT,
    ACTIONS(48), 1,
      sym_comment_end_tag,
    ACTIONS(50), 1,
      anon_sym_LT_SLASH,
    ACTIONS(53), 1,
      sym_text,
    STATE(5), 1,
      sym_start_tag,
    STATE(21), 1,
      sym_self_closing_tag,
    STATE(62), 1,
      sym_script_start_tag,
    STATE(66), 1,
      sym_style_start_tag,
    STATE(6), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_comment_repeat1,
  [217] = 11,
    ACTIONS(5), 1,
      anon_sym_LT_BANG,
    ACTIONS(7), 1,
      sym_comment_start_tag,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(56), 1,
      sym_comment_end_tag,
    ACTIONS(58), 1,
      sym_text,
    STATE(5), 1,
      sym_start_tag,
    STATE(21), 1,
      sym_self_closing_tag,
    STATE(62), 1,
      sym_script_start_tag,
    STATE(66), 1,
      sym_style_start_tag,
    STATE(6), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_comment_repeat1,
  [258] = 11,
    ACTIONS(5), 1,
      anon_sym_LT_BANG,
    ACTIONS(7), 1,
      sym_comment_start_tag,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(58), 1,
      sym_text,
    ACTIONS(60), 1,
      sym_comment_end_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(21), 1,
      sym_self_closing_tag,
    STATE(62), 1,
      sym_script_start_tag,
    STATE(66), 1,
      sym_style_start_tag,
    STATE(6), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_comment_repeat1,
  [299] = 11,
    ACTIONS(5), 1,
      anon_sym_LT_BANG,
    ACTIONS(7), 1,
      sym_comment_start_tag,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(62), 1,
      sym_comment_end_tag,
    ACTIONS(64), 1,
      sym_text,
    STATE(5), 1,
      sym_start_tag,
    STATE(21), 1,
      sym_self_closing_tag,
    STATE(62), 1,
      sym_script_start_tag,
    STATE(66), 1,
      sym_style_start_tag,
    STATE(8), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_comment_repeat1,
  [340] = 11,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    ACTIONS(68), 1,
      anon_sym_LT_BANG,
    ACTIONS(71), 1,
      sym_comment_start_tag,
    ACTIONS(74), 1,
      anon_sym_LT,
    ACTIONS(77), 1,
      anon_sym_LT_SLASH,
    ACTIONS(80), 1,
      sym_text,
    STATE(5), 1,
      sym_start_tag,
    STATE(21), 1,
      sym_self_closing_tag,
    STATE(62), 1,
      sym_script_start_tag,
    STATE(66), 1,
      sym_style_start_tag,
    STATE(10), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [381] = 11,
    ACTIONS(5), 1,
      anon_sym_LT_BANG,
    ACTIONS(7), 1,
      sym_comment_start_tag,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    ACTIONS(85), 1,
      sym_text,
    STATE(5), 1,
      sym_start_tag,
    STATE(21), 1,
      sym_self_closing_tag,
    STATE(62), 1,
      sym_script_start_tag,
    STATE(66), 1,
      sym_style_start_tag,
    STATE(10), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [422] = 11,
    ACTIONS(48), 1,
      sym__implicit_end_tag,
    ACTIONS(87), 1,
      anon_sym_LT_BANG,
    ACTIONS(90), 1,
      sym_comment_start_tag,
    ACTIONS(93), 1,
      anon_sym_LT,
    ACTIONS(96), 1,
      anon_sym_LT_SLASH,
    ACTIONS(99), 1,
      sym_text,
    STATE(3), 1,
      sym_start_tag,
    STATE(42), 1,
      sym_self_closing_tag,
    STATE(63), 1,
      sym_style_start_tag,
    STATE(65), 1,
      sym_script_start_tag,
    STATE(12), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_comment_repeat1,
  [463] = 11,
    ACTIONS(5), 1,
      anon_sym_LT_BANG,
    ACTIONS(7), 1,
      sym_comment_start_tag,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(102), 1,
      sym_comment_end_tag,
    ACTIONS(104), 1,
      sym_text,
    STATE(5), 1,
      sym_start_tag,
    STATE(21), 1,
      sym_self_closing_tag,
    STATE(62), 1,
      sym_script_start_tag,
    STATE(66), 1,
      sym_style_start_tag,
    STATE(7), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_comment_repeat1,
  [504] = 2,
    ACTIONS(108), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(106), 5,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [516] = 2,
    ACTIONS(112), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(110), 5,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [528] = 2,
    ACTIONS(116), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(114), 5,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [540] = 2,
    ACTIONS(120), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(118), 5,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [552] = 2,
    ACTIONS(124), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(122), 5,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [564] = 2,
    ACTIONS(128), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(126), 5,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [576] = 2,
    ACTIONS(132), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(130), 5,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [588] = 2,
    ACTIONS(136), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(134), 5,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [600] = 2,
    ACTIONS(140), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(138), 5,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [612] = 2,
    ACTIONS(144), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(142), 5,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [624] = 2,
    ACTIONS(148), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(146), 5,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [636] = 2,
    ACTIONS(152), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(150), 5,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [648] = 2,
    ACTIONS(156), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(154), 5,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [660] = 2,
    ACTIONS(160), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(158), 5,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [672] = 2,
    ACTIONS(108), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(106), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [683] = 2,
    ACTIONS(132), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(130), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [694] = 2,
    ACTIONS(144), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(142), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [705] = 2,
    ACTIONS(162), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(164), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [716] = 2,
    ACTIONS(112), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(110), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [727] = 2,
    ACTIONS(116), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(114), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [738] = 2,
    ACTIONS(152), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(150), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [749] = 2,
    ACTIONS(148), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(146), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [760] = 2,
    ACTIONS(128), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(126), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [771] = 2,
    ACTIONS(120), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(118), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [782] = 2,
    ACTIONS(140), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(138), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [793] = 2,
    ACTIONS(124), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(122), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [804] = 2,
    ACTIONS(156), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(154), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [815] = 2,
    ACTIONS(160), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(158), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [826] = 2,
    ACTIONS(136), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(134), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [837] = 2,
    ACTIONS(166), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(168), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [848] = 4,
    ACTIONS(170), 1,
      anon_sym_GT,
    ACTIONS(172), 1,
      anon_sym_SLASH_GT,
    ACTIONS(174), 1,
      sym_attribute_name,
    STATE(48), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [862] = 4,
    ACTIONS(170), 1,
      anon_sym_GT,
    ACTIONS(174), 1,
      sym_attribute_name,
    ACTIONS(176), 1,
      anon_sym_SLASH_GT,
    STATE(48), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [876] = 4,
    ACTIONS(174), 1,
      sym_attribute_name,
    ACTIONS(178), 1,
      anon_sym_GT,
    ACTIONS(180), 1,
      anon_sym_SLASH_GT,
    STATE(45), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [890] = 4,
    ACTIONS(174), 1,
      sym_attribute_name,
    ACTIONS(178), 1,
      anon_sym_GT,
    ACTIONS(182), 1,
      anon_sym_SLASH_GT,
    STATE(44), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [904] = 3,
    ACTIONS(186), 1,
      sym_attribute_name,
    ACTIONS(184), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(48), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [916] = 3,
    ACTIONS(184), 1,
      anon_sym_GT,
    ACTIONS(189), 1,
      sym_attribute_name,
    STATE(49), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [927] = 4,
    ACTIONS(192), 1,
      sym_attribute_value,
    ACTIONS(194), 1,
      anon_sym_SQUOTE,
    ACTIONS(196), 1,
      anon_sym_DQUOTE,
    STATE(67), 1,
      sym_quoted_attribute_value,
  [940] = 4,
    ACTIONS(198), 1,
      sym_attribute_value,
    ACTIONS(200), 1,
      anon_sym_SQUOTE,
    ACTIONS(202), 1,
      anon_sym_DQUOTE,
    STATE(59), 1,
      sym_quoted_attribute_value,
  [953] = 3,
    ACTIONS(204), 1,
      anon_sym_GT,
    ACTIONS(206), 1,
      sym_attribute_name,
    STATE(49), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [964] = 3,
    ACTIONS(206), 1,
      sym_attribute_name,
    ACTIONS(208), 1,
      anon_sym_GT,
    STATE(54), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [975] = 3,
    ACTIONS(206), 1,
      sym_attribute_name,
    ACTIONS(210), 1,
      anon_sym_GT,
    STATE(49), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [986] = 3,
    ACTIONS(206), 1,
      sym_attribute_name,
    ACTIONS(212), 1,
      anon_sym_GT,
    STATE(52), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [997] = 2,
    ACTIONS(216), 1,
      anon_sym_EQ,
    ACTIONS(214), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1006] = 2,
    ACTIONS(218), 1,
      anon_sym_EQ,
    ACTIONS(214), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1014] = 3,
    ACTIONS(220), 1,
      sym__start_tag_name,
    ACTIONS(222), 1,
      sym__script_start_tag_name,
    ACTIONS(224), 1,
      sym__style_start_tag_name,
  [1024] = 1,
    ACTIONS(226), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1030] = 3,
    ACTIONS(222), 1,
      sym__script_start_tag_name,
    ACTIONS(224), 1,
      sym__style_start_tag_name,
    ACTIONS(228), 1,
      sym__start_tag_name,
  [1040] = 1,
    ACTIONS(230), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1046] = 3,
    ACTIONS(232), 1,
      anon_sym_LT_SLASH,
    ACTIONS(234), 1,
      sym_raw_text,
    STATE(24), 1,
      sym_end_tag,
  [1056] = 3,
    ACTIONS(236), 1,
      anon_sym_LT_SLASH,
    ACTIONS(238), 1,
      sym_raw_text,
    STATE(34), 1,
      sym_end_tag,
  [1066] = 1,
    ACTIONS(240), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1072] = 3,
    ACTIONS(236), 1,
      anon_sym_LT_SLASH,
    ACTIONS(242), 1,
      sym_raw_text,
    STATE(35), 1,
      sym_end_tag,
  [1082] = 3,
    ACTIONS(232), 1,
      anon_sym_LT_SLASH,
    ACTIONS(244), 1,
      sym_raw_text,
    STATE(25), 1,
      sym_end_tag,
  [1092] = 1,
    ACTIONS(226), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1097] = 2,
    ACTIONS(246), 1,
      anon_sym_DQUOTE,
    ACTIONS(248), 1,
      aux_sym_quoted_attribute_value_token2,
  [1104] = 2,
    ACTIONS(232), 1,
      anon_sym_LT_SLASH,
    STATE(18), 1,
      sym_end_tag,
  [1111] = 2,
    ACTIONS(250), 1,
      sym__end_tag_name,
    ACTIONS(252), 1,
      sym_erroneous_end_tag_name,
  [1118] = 2,
    ACTIONS(232), 1,
      anon_sym_LT_SLASH,
    STATE(17), 1,
      sym_end_tag,
  [1125] = 2,
    ACTIONS(252), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(254), 1,
      sym__end_tag_name,
  [1132] = 2,
    ACTIONS(246), 1,
      anon_sym_SQUOTE,
    ACTIONS(256), 1,
      aux_sym_quoted_attribute_value_token1,
  [1139] = 1,
    ACTIONS(258), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1144] = 1,
    ACTIONS(260), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1149] = 1,
    ACTIONS(262), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1154] = 1,
    ACTIONS(230), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1159] = 1,
    ACTIONS(240), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1164] = 2,
    ACTIONS(264), 1,
      anon_sym_DQUOTE,
    ACTIONS(266), 1,
      aux_sym_quoted_attribute_value_token2,
  [1171] = 1,
    ACTIONS(268), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1176] = 2,
    ACTIONS(264), 1,
      anon_sym_SQUOTE,
    ACTIONS(270), 1,
      aux_sym_quoted_attribute_value_token1,
  [1183] = 2,
    ACTIONS(236), 1,
      anon_sym_LT_SLASH,
    STATE(39), 1,
      sym_end_tag,
  [1190] = 2,
    ACTIONS(236), 1,
      anon_sym_LT_SLASH,
    STATE(37), 1,
      sym_end_tag,
  [1197] = 1,
    ACTIONS(272), 1,
      ts_builtin_sym_end,
  [1201] = 1,
    ACTIONS(274), 1,
      anon_sym_GT,
  [1205] = 1,
    ACTIONS(276), 1,
      sym_erroneous_end_tag_name,
  [1209] = 1,
    ACTIONS(278), 1,
      anon_sym_DQUOTE,
  [1213] = 1,
    ACTIONS(280), 1,
      sym__doctype,
  [1217] = 1,
    ACTIONS(282), 1,
      anon_sym_GT,
  [1221] = 1,
    ACTIONS(278), 1,
      anon_sym_SQUOTE,
  [1225] = 1,
    ACTIONS(284), 1,
      anon_sym_GT,
  [1229] = 1,
    ACTIONS(286), 1,
      anon_sym_GT,
  [1233] = 1,
    ACTIONS(288), 1,
      anon_sym_GT,
  [1237] = 1,
    ACTIONS(290), 1,
      aux_sym_doctype_token1,
  [1241] = 1,
    ACTIONS(292), 1,
      anon_sym_SQUOTE,
  [1245] = 1,
    ACTIONS(292), 1,
      anon_sym_DQUOTE,
  [1249] = 1,
    ACTIONS(294), 1,
      anon_sym_GT,
  [1253] = 1,
    ACTIONS(252), 1,
      sym_erroneous_end_tag_name,
  [1257] = 1,
    ACTIONS(296), 1,
      aux_sym_doctype_token1,
  [1261] = 1,
    ACTIONS(254), 1,
      sym__end_tag_name,
  [1265] = 1,
    ACTIONS(250), 1,
      sym__end_tag_name,
  [1269] = 1,
    ACTIONS(298), 1,
      sym__doctype,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 44,
  [SMALL_STATE(4)] = 88,
  [SMALL_STATE(5)] = 132,
  [SMALL_STATE(6)] = 176,
  [SMALL_STATE(7)] = 217,
  [SMALL_STATE(8)] = 258,
  [SMALL_STATE(9)] = 299,
  [SMALL_STATE(10)] = 340,
  [SMALL_STATE(11)] = 381,
  [SMALL_STATE(12)] = 422,
  [SMALL_STATE(13)] = 463,
  [SMALL_STATE(14)] = 504,
  [SMALL_STATE(15)] = 516,
  [SMALL_STATE(16)] = 528,
  [SMALL_STATE(17)] = 540,
  [SMALL_STATE(18)] = 552,
  [SMALL_STATE(19)] = 564,
  [SMALL_STATE(20)] = 576,
  [SMALL_STATE(21)] = 588,
  [SMALL_STATE(22)] = 600,
  [SMALL_STATE(23)] = 612,
  [SMALL_STATE(24)] = 624,
  [SMALL_STATE(25)] = 636,
  [SMALL_STATE(26)] = 648,
  [SMALL_STATE(27)] = 660,
  [SMALL_STATE(28)] = 672,
  [SMALL_STATE(29)] = 683,
  [SMALL_STATE(30)] = 694,
  [SMALL_STATE(31)] = 705,
  [SMALL_STATE(32)] = 716,
  [SMALL_STATE(33)] = 727,
  [SMALL_STATE(34)] = 738,
  [SMALL_STATE(35)] = 749,
  [SMALL_STATE(36)] = 760,
  [SMALL_STATE(37)] = 771,
  [SMALL_STATE(38)] = 782,
  [SMALL_STATE(39)] = 793,
  [SMALL_STATE(40)] = 804,
  [SMALL_STATE(41)] = 815,
  [SMALL_STATE(42)] = 826,
  [SMALL_STATE(43)] = 837,
  [SMALL_STATE(44)] = 848,
  [SMALL_STATE(45)] = 862,
  [SMALL_STATE(46)] = 876,
  [SMALL_STATE(47)] = 890,
  [SMALL_STATE(48)] = 904,
  [SMALL_STATE(49)] = 916,
  [SMALL_STATE(50)] = 927,
  [SMALL_STATE(51)] = 940,
  [SMALL_STATE(52)] = 953,
  [SMALL_STATE(53)] = 964,
  [SMALL_STATE(54)] = 975,
  [SMALL_STATE(55)] = 986,
  [SMALL_STATE(56)] = 997,
  [SMALL_STATE(57)] = 1006,
  [SMALL_STATE(58)] = 1014,
  [SMALL_STATE(59)] = 1024,
  [SMALL_STATE(60)] = 1030,
  [SMALL_STATE(61)] = 1040,
  [SMALL_STATE(62)] = 1046,
  [SMALL_STATE(63)] = 1056,
  [SMALL_STATE(64)] = 1066,
  [SMALL_STATE(65)] = 1072,
  [SMALL_STATE(66)] = 1082,
  [SMALL_STATE(67)] = 1092,
  [SMALL_STATE(68)] = 1097,
  [SMALL_STATE(69)] = 1104,
  [SMALL_STATE(70)] = 1111,
  [SMALL_STATE(71)] = 1118,
  [SMALL_STATE(72)] = 1125,
  [SMALL_STATE(73)] = 1132,
  [SMALL_STATE(74)] = 1139,
  [SMALL_STATE(75)] = 1144,
  [SMALL_STATE(76)] = 1149,
  [SMALL_STATE(77)] = 1154,
  [SMALL_STATE(78)] = 1159,
  [SMALL_STATE(79)] = 1164,
  [SMALL_STATE(80)] = 1171,
  [SMALL_STATE(81)] = 1176,
  [SMALL_STATE(82)] = 1183,
  [SMALL_STATE(83)] = 1190,
  [SMALL_STATE(84)] = 1197,
  [SMALL_STATE(85)] = 1201,
  [SMALL_STATE(86)] = 1205,
  [SMALL_STATE(87)] = 1209,
  [SMALL_STATE(88)] = 1213,
  [SMALL_STATE(89)] = 1217,
  [SMALL_STATE(90)] = 1221,
  [SMALL_STATE(91)] = 1225,
  [SMALL_STATE(92)] = 1229,
  [SMALL_STATE(93)] = 1233,
  [SMALL_STATE(94)] = 1237,
  [SMALL_STATE(95)] = 1241,
  [SMALL_STATE(96)] = 1245,
  [SMALL_STATE(97)] = 1249,
  [SMALL_STATE(98)] = 1253,
  [SMALL_STATE(99)] = 1257,
  [SMALL_STATE(100)] = 1261,
  [SMALL_STATE(101)] = 1265,
  [SMALL_STATE(102)] = 1269,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(88),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(13),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(60),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(86),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(6),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(88),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(13),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(60),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(86),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(10),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 1),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(102),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(9),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(58),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(98),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(12),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erroneous_end_tag, 3),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_erroneous_end_tag, 3),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 4),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 4),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2),
  [186] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(56),
  [189] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(57),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [246] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4),
  [264] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [272] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_html_external_scanner_create(void);
void tree_sitter_html_external_scanner_destroy(void *);
bool tree_sitter_html_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_html_external_scanner_serialize(void *, char *);
void tree_sitter_html_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_html(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_html_external_scanner_create,
      tree_sitter_html_external_scanner_destroy,
      tree_sitter_html_external_scanner_scan,
      tree_sitter_html_external_scanner_serialize,
      tree_sitter_html_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
