#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 155
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 9
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_LT_BANG = 1,
  aux_sym_doctype_token1 = 2,
  anon_sym_GT = 3,
  sym__doctype = 4,
  sym_comment_start_tag = 5,
  anon_sym_LT = 6,
  anon_sym_SLASH_GT = 7,
  anon_sym_LT_SLASH_GT = 8,
  sym_comment_end_tag = 9,
  anon_sym_LT_SLASH = 10,
  anon_sym_EQ = 11,
  sym_attribute_name = 12,
  sym_attribute_value = 13,
  anon_sym_SQUOTE = 14,
  aux_sym_quoted_attribute_value_token1 = 15,
  anon_sym_DQUOTE = 16,
  aux_sym_quoted_attribute_value_token2 = 17,
  sym__start_tag_name = 18,
  sym__script_start_tag_name = 19,
  sym__style_start_tag_name = 20,
  sym__end_tag_name = 21,
  sym_erroneous_end_tag_name = 22,
  sym__implicit_end_tag = 23,
  sym_raw_text = 24,
  sym_text = 25,
  sym_fragment = 26,
  sym_doctype = 27,
  sym__node = 28,
  sym_comment = 29,
  sym_element = 30,
  sym_script_element = 31,
  sym_style_element = 32,
  sym_start_tag = 33,
  sym_script_start_tag = 34,
  sym_style_start_tag = 35,
  sym_self_closing_tag = 36,
  sym_end_tag = 37,
  sym_erroneous_end_tag = 38,
  sym_attribute = 39,
  sym_quoted_attribute_value = 40,
  aux_sym_fragment_repeat1 = 41,
  aux_sym_start_tag_repeat1 = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG] = "<!",
  [aux_sym_doctype_token1] = "doctype_token1",
  [anon_sym_GT] = ">",
  [sym__doctype] = "doctype",
  [sym_comment_start_tag] = "comment_start_tag",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH_GT] = "</>",
  [sym_comment_end_tag] = "comment_end_tag",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token1] = "attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token2] = "attribute_value",
  [sym__start_tag_name] = "tag_name",
  [sym__script_start_tag_name] = "tag_name",
  [sym__style_start_tag_name] = "tag_name",
  [sym__end_tag_name] = "tag_name",
  [sym_erroneous_end_tag_name] = "erroneous_end_tag_name",
  [sym__implicit_end_tag] = "_implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_text] = "text",
  [sym_fragment] = "fragment",
  [sym_doctype] = "doctype",
  [sym__node] = "_node",
  [sym_comment] = "comment",
  [sym_element] = "element",
  [sym_script_element] = "script_element",
  [sym_style_element] = "style_element",
  [sym_start_tag] = "start_tag",
  [sym_script_start_tag] = "start_tag",
  [sym_style_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_erroneous_end_tag] = "erroneous_end_tag",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [aux_sym_fragment_repeat1] = "fragment_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [aux_sym_doctype_token1] = aux_sym_doctype_token1,
  [anon_sym_GT] = anon_sym_GT,
  [sym__doctype] = sym__doctype,
  [sym_comment_start_tag] = sym_comment_start_tag,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH_GT] = anon_sym_LT_SLASH_GT,
  [sym_comment_end_tag] = sym_comment_end_tag,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token1] = sym_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token2] = sym_attribute_value,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__script_start_tag_name] = sym__start_tag_name,
  [sym__style_start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [sym__implicit_end_tag] = sym__implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_text] = sym_text,
  [sym_fragment] = sym_fragment,
  [sym_doctype] = sym_doctype,
  [sym__node] = sym__node,
  [sym_comment] = sym_comment,
  [sym_element] = sym_element,
  [sym_script_element] = sym_script_element,
  [sym_style_element] = sym_style_element,
  [sym_start_tag] = sym_start_tag,
  [sym_script_start_tag] = sym_start_tag,
  [sym_style_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_erroneous_end_tag] = sym_erroneous_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [aux_sym_fragment_repeat1] = aux_sym_fragment_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doctype_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym__doctype] = {
    .visible = true,
    .named = false,
  },
  [sym_comment_start_tag] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_comment_end_tag] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__implicit_end_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '\'') ADVANCE(31);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '<') ADVANCE(23);
      if (lookahead == '=') ADVANCE(28);
      if (lookahead == '>') ADVANCE(20);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '\'') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(30);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(22);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '=') ADVANCE(28);
      if (lookahead == '>') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '<') ADVANCE(29);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(26);
      END_STATE();
    case 9:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 11:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(14);
      END_STATE();
    case 14:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(19);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      if (lookahead == '-') ADVANCE(4);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__doctype);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_comment_start_tag);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(17);
      if (lookahead == '/') ADVANCE(27);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LT_SLASH_GT);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_comment_end_tag);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      if (lookahead == '>') ADVANCE(25);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(36);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 3},
  [3] = {.lex_state = 0, .external_lex_state = 3},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 3},
  [7] = {.lex_state = 0, .external_lex_state = 3},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 0, .external_lex_state = 2},
  [13] = {.lex_state = 0, .external_lex_state = 3},
  [14] = {.lex_state = 0, .external_lex_state = 2},
  [15] = {.lex_state = 0, .external_lex_state = 2},
  [16] = {.lex_state = 0, .external_lex_state = 2},
  [17] = {.lex_state = 0, .external_lex_state = 2},
  [18] = {.lex_state = 6, .external_lex_state = 4},
  [19] = {.lex_state = 6, .external_lex_state = 4},
  [20] = {.lex_state = 6, .external_lex_state = 4},
  [21] = {.lex_state = 0, .external_lex_state = 3},
  [22] = {.lex_state = 0, .external_lex_state = 3},
  [23] = {.lex_state = 0, .external_lex_state = 2},
  [24] = {.lex_state = 0, .external_lex_state = 2},
  [25] = {.lex_state = 0, .external_lex_state = 2},
  [26] = {.lex_state = 0, .external_lex_state = 2},
  [27] = {.lex_state = 0, .external_lex_state = 2},
  [28] = {.lex_state = 0, .external_lex_state = 2},
  [29] = {.lex_state = 0, .external_lex_state = 2},
  [30] = {.lex_state = 0, .external_lex_state = 3},
  [31] = {.lex_state = 0, .external_lex_state = 2},
  [32] = {.lex_state = 0, .external_lex_state = 3},
  [33] = {.lex_state = 0, .external_lex_state = 2},
  [34] = {.lex_state = 0, .external_lex_state = 3},
  [35] = {.lex_state = 0, .external_lex_state = 2},
  [36] = {.lex_state = 0, .external_lex_state = 3},
  [37] = {.lex_state = 0, .external_lex_state = 2},
  [38] = {.lex_state = 0, .external_lex_state = 3},
  [39] = {.lex_state = 0, .external_lex_state = 3},
  [40] = {.lex_state = 0, .external_lex_state = 3},
  [41] = {.lex_state = 0, .external_lex_state = 3},
  [42] = {.lex_state = 0, .external_lex_state = 3},
  [43] = {.lex_state = 0, .external_lex_state = 3},
  [44] = {.lex_state = 0, .external_lex_state = 3},
  [45] = {.lex_state = 0, .external_lex_state = 3},
  [46] = {.lex_state = 0, .external_lex_state = 2},
  [47] = {.lex_state = 0, .external_lex_state = 3},
  [48] = {.lex_state = 0, .external_lex_state = 2},
  [49] = {.lex_state = 0, .external_lex_state = 2},
  [50] = {.lex_state = 0, .external_lex_state = 2},
  [51] = {.lex_state = 0, .external_lex_state = 2},
  [52] = {.lex_state = 0, .external_lex_state = 2},
  [53] = {.lex_state = 0, .external_lex_state = 3},
  [54] = {.lex_state = 0, .external_lex_state = 2},
  [55] = {.lex_state = 0, .external_lex_state = 3},
  [56] = {.lex_state = 0, .external_lex_state = 3},
  [57] = {.lex_state = 0, .external_lex_state = 3},
  [58] = {.lex_state = 0, .external_lex_state = 3},
  [59] = {.lex_state = 0, .external_lex_state = 3},
  [60] = {.lex_state = 0, .external_lex_state = 2},
  [61] = {.lex_state = 0, .external_lex_state = 3},
  [62] = {.lex_state = 0, .external_lex_state = 3},
  [63] = {.lex_state = 0, .external_lex_state = 2},
  [64] = {.lex_state = 0, .external_lex_state = 2},
  [65] = {.lex_state = 0, .external_lex_state = 2},
  [66] = {.lex_state = 0, .external_lex_state = 2},
  [67] = {.lex_state = 0, .external_lex_state = 2},
  [68] = {.lex_state = 0, .external_lex_state = 2},
  [69] = {.lex_state = 0, .external_lex_state = 2},
  [70] = {.lex_state = 0, .external_lex_state = 2},
  [71] = {.lex_state = 0, .external_lex_state = 2},
  [72] = {.lex_state = 0, .external_lex_state = 3},
  [73] = {.lex_state = 0, .external_lex_state = 2},
  [74] = {.lex_state = 0, .external_lex_state = 2},
  [75] = {.lex_state = 0, .external_lex_state = 2},
  [76] = {.lex_state = 0, .external_lex_state = 2},
  [77] = {.lex_state = 0, .external_lex_state = 2},
  [78] = {.lex_state = 0, .external_lex_state = 2},
  [79] = {.lex_state = 0, .external_lex_state = 2},
  [80] = {.lex_state = 0, .external_lex_state = 2},
  [81] = {.lex_state = 6, .external_lex_state = 5},
  [82] = {.lex_state = 6, .external_lex_state = 5},
  [83] = {.lex_state = 6, .external_lex_state = 5},
  [84] = {.lex_state = 6, .external_lex_state = 5},
  [85] = {.lex_state = 6, .external_lex_state = 5},
  [86] = {.lex_state = 6, .external_lex_state = 5},
  [87] = {.lex_state = 6, .external_lex_state = 5},
  [88] = {.lex_state = 6, .external_lex_state = 5},
  [89] = {.lex_state = 6, .external_lex_state = 5},
  [90] = {.lex_state = 6, .external_lex_state = 5},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 0, .external_lex_state = 6},
  [93] = {.lex_state = 1},
  [94] = {.lex_state = 6},
  [95] = {.lex_state = 0, .external_lex_state = 6},
  [96] = {.lex_state = 0, .external_lex_state = 6},
  [97] = {.lex_state = 0, .external_lex_state = 6},
  [98] = {.lex_state = 6},
  [99] = {.lex_state = 6},
  [100] = {.lex_state = 6, .external_lex_state = 5},
  [101] = {.lex_state = 0, .external_lex_state = 6},
  [102] = {.lex_state = 6},
  [103] = {.lex_state = 0, .external_lex_state = 6},
  [104] = {.lex_state = 6},
  [105] = {.lex_state = 0, .external_lex_state = 6},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0, .external_lex_state = 6},
  [110] = {.lex_state = 0, .external_lex_state = 6},
  [111] = {.lex_state = 0, .external_lex_state = 7},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 6},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 6, .external_lex_state = 5},
  [116] = {.lex_state = 0, .external_lex_state = 7},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 6, .external_lex_state = 5},
  [119] = {.lex_state = 0, .external_lex_state = 6},
  [120] = {.lex_state = 6, .external_lex_state = 5},
  [121] = {.lex_state = 0, .external_lex_state = 7},
  [122] = {.lex_state = 3},
  [123] = {.lex_state = 3},
  [124] = {.lex_state = 0, .external_lex_state = 8},
  [125] = {.lex_state = 0, .external_lex_state = 8},
  [126] = {.lex_state = 0, .external_lex_state = 8},
  [127] = {.lex_state = 6},
  [128] = {.lex_state = 6},
  [129] = {.lex_state = 6},
  [130] = {.lex_state = 2},
  [131] = {.lex_state = 2},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0, .external_lex_state = 9},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0, .external_lex_state = 9},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 15},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 15},
  [151] = {.lex_state = 0, .external_lex_state = 9},
  [152] = {.lex_state = 15},
  [153] = {.lex_state = 0},
  [154] = {.lex_state = 0},
};

enum {
  ts_external_token__start_tag_name = 0,
  ts_external_token__script_start_tag_name = 1,
  ts_external_token__style_start_tag_name = 2,
  ts_external_token__end_tag_name = 3,
  ts_external_token_erroneous_end_tag_name = 4,
  ts_external_token_SLASH_GT = 5,
  ts_external_token__implicit_end_tag = 6,
  ts_external_token_raw_text = 7,
  ts_external_token_text = 8,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__script_start_tag_name] = sym__script_start_tag_name,
  [ts_external_token__style_start_tag_name] = sym__style_start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token__implicit_end_tag] = sym__implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_text] = sym_text,
};

static const bool ts_external_scanner_states[10][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_text] = true,
  },
  [2] = {
    [ts_external_token_text] = true,
  },
  [3] = {
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_text] = true,
  },
  [4] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
  },
  [5] = {
    [ts_external_token_SLASH_GT] = true,
  },
  [6] = {
    [ts_external_token_raw_text] = true,
  },
  [7] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
  },
  [8] = {
    [ts_external_token__end_tag_name] = true,
  },
  [9] = {
    [ts_external_token_erroneous_end_tag_name] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym__doctype] = ACTIONS(1),
    [sym_comment_start_tag] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH_GT] = ACTIONS(1),
    [sym_comment_end_tag] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__script_start_tag_name] = ACTIONS(1),
    [sym__style_start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym_erroneous_end_tag_name] = ACTIONS(1),
    [sym__implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
  },
  [1] = {
    [sym_fragment] = STATE(135),
    [sym_doctype] = STATE(11),
    [sym__node] = STATE(11),
    [sym_comment] = STATE(11),
    [sym_element] = STATE(11),
    [sym_script_element] = STATE(11),
    [sym_style_element] = STATE(11),
    [sym_start_tag] = STATE(4),
    [sym_script_start_tag] = STATE(92),
    [sym_style_start_tag] = STATE(95),
    [sym_self_closing_tag] = STATE(27),
    [sym_erroneous_end_tag] = STATE(11),
    [aux_sym_fragment_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT_BANG] = ACTIONS(5),
    [sym_comment_start_tag] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LT_SLASH_GT] = ACTIONS(11),
    [anon_sym_LT_SLASH] = ACTIONS(13),
    [sym_text] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      sym_comment_start_tag,
    ACTIONS(21), 1,
      anon_sym_LT,
    ACTIONS(23), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(25), 1,
      anon_sym_LT_SLASH,
    ACTIONS(27), 1,
      sym__implicit_end_tag,
    ACTIONS(29), 1,
      sym_text,
    STATE(3), 1,
      sym_start_tag,
    STATE(61), 1,
      sym_self_closing_tag,
    STATE(70), 1,
      sym_end_tag,
    STATE(101), 1,
      sym_script_start_tag,
    STATE(103), 1,
      sym_style_start_tag,
    STATE(7), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [47] = 13,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      sym_comment_start_tag,
    ACTIONS(21), 1,
      anon_sym_LT,
    ACTIONS(31), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(33), 1,
      anon_sym_LT_SLASH,
    ACTIONS(35), 1,
      sym__implicit_end_tag,
    ACTIONS(37), 1,
      sym_text,
    STATE(3), 1,
      sym_start_tag,
    STATE(57), 1,
      sym_end_tag,
    STATE(61), 1,
      sym_self_closing_tag,
    STATE(101), 1,
      sym_script_start_tag,
    STATE(103), 1,
      sym_style_start_tag,
    STATE(6), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [94] = 13,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      sym_comment_start_tag,
    ACTIONS(21), 1,
      anon_sym_LT,
    ACTIONS(39), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(41), 1,
      anon_sym_LT_SLASH,
    ACTIONS(43), 1,
      sym__implicit_end_tag,
    ACTIONS(45), 1,
      sym_text,
    STATE(3), 1,
      sym_start_tag,
    STATE(28), 1,
      sym_end_tag,
    STATE(61), 1,
      sym_self_closing_tag,
    STATE(101), 1,
      sym_script_start_tag,
    STATE(103), 1,
      sym_style_start_tag,
    STATE(5), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [141] = 13,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      sym_comment_start_tag,
    ACTIONS(21), 1,
      anon_sym_LT,
    ACTIONS(39), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(41), 1,
      anon_sym_LT_SLASH,
    ACTIONS(47), 1,
      sym__implicit_end_tag,
    ACTIONS(49), 1,
      sym_text,
    STATE(3), 1,
      sym_start_tag,
    STATE(49), 1,
      sym_end_tag,
    STATE(61), 1,
      sym_self_closing_tag,
    STATE(101), 1,
      sym_script_start_tag,
    STATE(103), 1,
      sym_style_start_tag,
    STATE(13), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [188] = 13,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      sym_comment_start_tag,
    ACTIONS(21), 1,
      anon_sym_LT,
    ACTIONS(31), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(33), 1,
      anon_sym_LT_SLASH,
    ACTIONS(49), 1,
      sym_text,
    ACTIONS(51), 1,
      sym__implicit_end_tag,
    STATE(3), 1,
      sym_start_tag,
    STATE(40), 1,
      sym_end_tag,
    STATE(61), 1,
      sym_self_closing_tag,
    STATE(101), 1,
      sym_script_start_tag,
    STATE(103), 1,
      sym_style_start_tag,
    STATE(13), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [235] = 13,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      sym_comment_start_tag,
    ACTIONS(21), 1,
      anon_sym_LT,
    ACTIONS(23), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(25), 1,
      anon_sym_LT_SLASH,
    ACTIONS(49), 1,
      sym_text,
    ACTIONS(53), 1,
      sym__implicit_end_tag,
    STATE(3), 1,
      sym_start_tag,
    STATE(61), 1,
      sym_self_closing_tag,
    STATE(77), 1,
      sym_end_tag,
    STATE(101), 1,
      sym_script_start_tag,
    STATE(103), 1,
      sym_style_start_tag,
    STATE(13), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [282] = 12,
    ACTIONS(55), 1,
      anon_sym_LT_BANG,
    ACTIONS(57), 1,
      sym_comment_start_tag,
    ACTIONS(59), 1,
      anon_sym_LT,
    ACTIONS(61), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(63), 1,
      sym_comment_end_tag,
    ACTIONS(65), 1,
      anon_sym_LT_SLASH,
    ACTIONS(67), 1,
      sym_text,
    STATE(2), 1,
      sym_start_tag,
    STATE(66), 1,
      sym_self_closing_tag,
    STATE(96), 1,
      sym_style_start_tag,
    STATE(97), 1,
      sym_script_start_tag,
    STATE(14), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [326] = 12,
    ACTIONS(55), 1,
      anon_sym_LT_BANG,
    ACTIONS(57), 1,
      sym_comment_start_tag,
    ACTIONS(59), 1,
      anon_sym_LT,
    ACTIONS(61), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(65), 1,
      anon_sym_LT_SLASH,
    ACTIONS(69), 1,
      sym_comment_end_tag,
    ACTIONS(71), 1,
      sym_text,
    STATE(2), 1,
      sym_start_tag,
    STATE(66), 1,
      sym_self_closing_tag,
    STATE(96), 1,
      sym_style_start_tag,
    STATE(97), 1,
      sym_script_start_tag,
    STATE(17), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [370] = 12,
    ACTIONS(55), 1,
      anon_sym_LT_BANG,
    ACTIONS(57), 1,
      sym_comment_start_tag,
    ACTIONS(59), 1,
      anon_sym_LT,
    ACTIONS(61), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(65), 1,
      anon_sym_LT_SLASH,
    ACTIONS(73), 1,
      sym_comment_end_tag,
    ACTIONS(75), 1,
      sym_text,
    STATE(2), 1,
      sym_start_tag,
    STATE(66), 1,
      sym_self_closing_tag,
    STATE(96), 1,
      sym_style_start_tag,
    STATE(97), 1,
      sym_script_start_tag,
    STATE(15), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [414] = 12,
    ACTIONS(5), 1,
      anon_sym_LT_BANG,
    ACTIONS(7), 1,
      sym_comment_start_tag,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(13), 1,
      anon_sym_LT_SLASH,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    ACTIONS(79), 1,
      sym_text,
    STATE(4), 1,
      sym_start_tag,
    STATE(27), 1,
      sym_self_closing_tag,
    STATE(92), 1,
      sym_script_start_tag,
    STATE(95), 1,
      sym_style_start_tag,
    STATE(16), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [458] = 12,
    ACTIONS(55), 1,
      anon_sym_LT_BANG,
    ACTIONS(57), 1,
      sym_comment_start_tag,
    ACTIONS(59), 1,
      anon_sym_LT,
    ACTIONS(61), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(65), 1,
      anon_sym_LT_SLASH,
    ACTIONS(81), 1,
      sym_comment_end_tag,
    ACTIONS(83), 1,
      sym_text,
    STATE(2), 1,
      sym_start_tag,
    STATE(66), 1,
      sym_self_closing_tag,
    STATE(96), 1,
      sym_style_start_tag,
    STATE(97), 1,
      sym_script_start_tag,
    STATE(10), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [502] = 12,
    ACTIONS(85), 1,
      anon_sym_LT_BANG,
    ACTIONS(88), 1,
      sym_comment_start_tag,
    ACTIONS(91), 1,
      anon_sym_LT,
    ACTIONS(94), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(97), 1,
      anon_sym_LT_SLASH,
    ACTIONS(100), 1,
      sym__implicit_end_tag,
    ACTIONS(102), 1,
      sym_text,
    STATE(3), 1,
      sym_start_tag,
    STATE(61), 1,
      sym_self_closing_tag,
    STATE(101), 1,
      sym_script_start_tag,
    STATE(103), 1,
      sym_style_start_tag,
    STATE(13), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [546] = 12,
    ACTIONS(55), 1,
      anon_sym_LT_BANG,
    ACTIONS(57), 1,
      sym_comment_start_tag,
    ACTIONS(59), 1,
      anon_sym_LT,
    ACTIONS(61), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(65), 1,
      anon_sym_LT_SLASH,
    ACTIONS(75), 1,
      sym_text,
    ACTIONS(105), 1,
      sym_comment_end_tag,
    STATE(2), 1,
      sym_start_tag,
    STATE(66), 1,
      sym_self_closing_tag,
    STATE(96), 1,
      sym_style_start_tag,
    STATE(97), 1,
      sym_script_start_tag,
    STATE(15), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [590] = 12,
    ACTIONS(100), 1,
      sym_comment_end_tag,
    ACTIONS(107), 1,
      anon_sym_LT_BANG,
    ACTIONS(110), 1,
      sym_comment_start_tag,
    ACTIONS(113), 1,
      anon_sym_LT,
    ACTIONS(116), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(119), 1,
      anon_sym_LT_SLASH,
    ACTIONS(122), 1,
      sym_text,
    STATE(2), 1,
      sym_start_tag,
    STATE(66), 1,
      sym_self_closing_tag,
    STATE(96), 1,
      sym_style_start_tag,
    STATE(97), 1,
      sym_script_start_tag,
    STATE(15), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [634] = 12,
    ACTIONS(100), 1,
      ts_builtin_sym_end,
    ACTIONS(125), 1,
      anon_sym_LT_BANG,
    ACTIONS(128), 1,
      sym_comment_start_tag,
    ACTIONS(131), 1,
      anon_sym_LT,
    ACTIONS(134), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(137), 1,
      anon_sym_LT_SLASH,
    ACTIONS(140), 1,
      sym_text,
    STATE(4), 1,
      sym_start_tag,
    STATE(27), 1,
      sym_self_closing_tag,
    STATE(92), 1,
      sym_script_start_tag,
    STATE(95), 1,
      sym_style_start_tag,
    STATE(16), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [678] = 12,
    ACTIONS(55), 1,
      anon_sym_LT_BANG,
    ACTIONS(57), 1,
      sym_comment_start_tag,
    ACTIONS(59), 1,
      anon_sym_LT,
    ACTIONS(61), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(65), 1,
      anon_sym_LT_SLASH,
    ACTIONS(75), 1,
      sym_text,
    ACTIONS(143), 1,
      sym_comment_end_tag,
    STATE(2), 1,
      sym_start_tag,
    STATE(66), 1,
      sym_self_closing_tag,
    STATE(96), 1,
      sym_style_start_tag,
    STATE(97), 1,
      sym_script_start_tag,
    STATE(15), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [722] = 7,
    ACTIONS(145), 1,
      anon_sym_GT,
    ACTIONS(147), 1,
      anon_sym_SLASH_GT,
    ACTIONS(149), 1,
      sym_attribute_name,
    ACTIONS(151), 1,
      sym__start_tag_name,
    ACTIONS(153), 1,
      sym__script_start_tag_name,
    ACTIONS(155), 1,
      sym__style_start_tag_name,
    STATE(88), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [745] = 7,
    ACTIONS(145), 1,
      anon_sym_GT,
    ACTIONS(149), 1,
      sym_attribute_name,
    ACTIONS(153), 1,
      sym__script_start_tag_name,
    ACTIONS(155), 1,
      sym__style_start_tag_name,
    ACTIONS(157), 1,
      anon_sym_SLASH_GT,
    ACTIONS(159), 1,
      sym__start_tag_name,
    STATE(86), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [768] = 7,
    ACTIONS(145), 1,
      anon_sym_GT,
    ACTIONS(149), 1,
      sym_attribute_name,
    ACTIONS(153), 1,
      sym__script_start_tag_name,
    ACTIONS(155), 1,
      sym__style_start_tag_name,
    ACTIONS(161), 1,
      anon_sym_SLASH_GT,
    ACTIONS(163), 1,
      sym__start_tag_name,
    STATE(81), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [791] = 4,
    ACTIONS(171), 1,
      sym_comment_end_tag,
    ACTIONS(173), 1,
      sym__implicit_end_tag,
    ACTIONS(165), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(168), 3,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [808] = 4,
    ACTIONS(171), 1,
      ts_builtin_sym_end,
    ACTIONS(173), 1,
      sym__implicit_end_tag,
    ACTIONS(165), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(168), 3,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [825] = 2,
    ACTIONS(177), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(175), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [837] = 2,
    ACTIONS(179), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(181), 4,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
      sym_comment_end_tag,
  [849] = 2,
    ACTIONS(183), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(173), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [861] = 2,
    ACTIONS(187), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(185), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [873] = 2,
    ACTIONS(191), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(189), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [885] = 2,
    ACTIONS(195), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(193), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [897] = 2,
    ACTIONS(199), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(197), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [909] = 2,
    ACTIONS(201), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(203), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [921] = 2,
    ACTIONS(205), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(171), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [933] = 2,
    ACTIONS(207), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(209), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [945] = 2,
    ACTIONS(213), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(211), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [957] = 2,
    ACTIONS(215), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(217), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [969] = 2,
    ACTIONS(221), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(219), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [981] = 2,
    ACTIONS(223), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(225), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [993] = 2,
    ACTIONS(229), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(227), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1005] = 2,
    ACTIONS(231), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(233), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1017] = 2,
    ACTIONS(235), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(237), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1029] = 2,
    ACTIONS(239), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(241), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1041] = 2,
    ACTIONS(243), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(245), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1053] = 2,
    ACTIONS(179), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(181), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1065] = 2,
    ACTIONS(177), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(175), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1077] = 2,
    ACTIONS(229), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(227), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1089] = 2,
    ACTIONS(221), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(219), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1101] = 2,
    ACTIONS(179), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(181), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1113] = 2,
    ACTIONS(213), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(211), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1125] = 2,
    ACTIONS(243), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(245), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1137] = 2,
    ACTIONS(239), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(241), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1149] = 2,
    ACTIONS(235), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(237), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1161] = 2,
    ACTIONS(223), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(225), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1173] = 2,
    ACTIONS(215), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(217), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1185] = 2,
    ACTIONS(247), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(249), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1197] = 2,
    ACTIONS(207), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(209), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1209] = 2,
    ACTIONS(205), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(171), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1221] = 2,
    ACTIONS(165), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(168), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1233] = 2,
    ACTIONS(195), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(193), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1245] = 2,
    ACTIONS(187), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(185), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1257] = 2,
    ACTIONS(199), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(197), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1269] = 2,
    ACTIONS(201), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(203), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1281] = 2,
    ACTIONS(191), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(189), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1293] = 2,
    ACTIONS(183), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(173), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1305] = 2,
    ACTIONS(201), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(203), 4,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
      sym_comment_end_tag,
  [1317] = 2,
    ACTIONS(207), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(209), 4,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
      sym_comment_end_tag,
  [1329] = 2,
    ACTIONS(183), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(173), 4,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
      sym_comment_end_tag,
  [1341] = 2,
    ACTIONS(191), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(189), 4,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
      sym_comment_end_tag,
  [1353] = 2,
    ACTIONS(199), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(197), 4,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
      sym_comment_end_tag,
  [1365] = 2,
    ACTIONS(187), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(185), 4,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
      sym_comment_end_tag,
  [1377] = 2,
    ACTIONS(215), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(217), 4,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
      sym_comment_end_tag,
  [1389] = 2,
    ACTIONS(195), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(193), 4,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
      sym_comment_end_tag,
  [1401] = 2,
    ACTIONS(223), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(225), 4,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
      sym_comment_end_tag,
  [1413] = 2,
    ACTIONS(251), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(253), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
  [1425] = 2,
    ACTIONS(205), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(171), 4,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
      sym_comment_end_tag,
  [1437] = 2,
    ACTIONS(213), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(211), 4,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
      sym_comment_end_tag,
  [1449] = 2,
    ACTIONS(235), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(237), 4,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
      sym_comment_end_tag,
  [1461] = 2,
    ACTIONS(221), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(219), 4,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
      sym_comment_end_tag,
  [1473] = 2,
    ACTIONS(239), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(241), 4,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
      sym_comment_end_tag,
  [1485] = 2,
    ACTIONS(229), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(227), 4,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
      sym_comment_end_tag,
  [1497] = 2,
    ACTIONS(177), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(175), 4,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
      sym_comment_end_tag,
  [1509] = 2,
    ACTIONS(243), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(245), 4,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH_GT,
      sym_comment_end_tag,
  [1521] = 4,
    ACTIONS(149), 1,
      sym_attribute_name,
    ACTIONS(255), 1,
      anon_sym_GT,
    ACTIONS(257), 1,
      anon_sym_SLASH_GT,
    STATE(83), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1535] = 4,
    ACTIONS(149), 1,
      sym_attribute_name,
    ACTIONS(259), 1,
      anon_sym_GT,
    ACTIONS(261), 1,
      anon_sym_SLASH_GT,
    STATE(83), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1549] = 3,
    ACTIONS(265), 1,
      sym_attribute_name,
    ACTIONS(263), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(83), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1561] = 4,
    ACTIONS(149), 1,
      sym_attribute_name,
    ACTIONS(255), 1,
      anon_sym_GT,
    ACTIONS(268), 1,
      anon_sym_SLASH_GT,
    STATE(89), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1575] = 4,
    ACTIONS(149), 1,
      sym_attribute_name,
    ACTIONS(259), 1,
      anon_sym_GT,
    ACTIONS(270), 1,
      anon_sym_SLASH_GT,
    STATE(83), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1589] = 4,
    ACTIONS(149), 1,
      sym_attribute_name,
    ACTIONS(255), 1,
      anon_sym_GT,
    ACTIONS(272), 1,
      anon_sym_SLASH_GT,
    STATE(83), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1603] = 4,
    ACTIONS(149), 1,
      sym_attribute_name,
    ACTIONS(255), 1,
      anon_sym_GT,
    ACTIONS(272), 1,
      anon_sym_SLASH_GT,
    STATE(85), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1617] = 4,
    ACTIONS(149), 1,
      sym_attribute_name,
    ACTIONS(255), 1,
      anon_sym_GT,
    ACTIONS(268), 1,
      anon_sym_SLASH_GT,
    STATE(83), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1631] = 4,
    ACTIONS(149), 1,
      sym_attribute_name,
    ACTIONS(259), 1,
      anon_sym_GT,
    ACTIONS(274), 1,
      anon_sym_SLASH_GT,
    STATE(83), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1645] = 4,
    ACTIONS(149), 1,
      sym_attribute_name,
    ACTIONS(255), 1,
      anon_sym_GT,
    ACTIONS(257), 1,
      anon_sym_SLASH_GT,
    STATE(82), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1659] = 4,
    ACTIONS(276), 1,
      sym_attribute_value,
    ACTIONS(278), 1,
      anon_sym_SQUOTE,
    ACTIONS(280), 1,
      anon_sym_DQUOTE,
    STATE(127), 1,
      sym_quoted_attribute_value,
  [1672] = 4,
    ACTIONS(282), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(284), 1,
      anon_sym_LT_SLASH,
    ACTIONS(286), 1,
      sym_raw_text,
    STATE(33), 1,
      sym_end_tag,
  [1685] = 4,
    ACTIONS(288), 1,
      sym_attribute_value,
    ACTIONS(290), 1,
      anon_sym_SQUOTE,
    ACTIONS(292), 1,
      anon_sym_DQUOTE,
    STATE(118), 1,
      sym_quoted_attribute_value,
  [1698] = 3,
    ACTIONS(263), 1,
      anon_sym_GT,
    ACTIONS(294), 1,
      sym_attribute_name,
    STATE(94), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1709] = 4,
    ACTIONS(282), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(284), 1,
      anon_sym_LT_SLASH,
    ACTIONS(297), 1,
      sym_raw_text,
    STATE(35), 1,
      sym_end_tag,
  [1722] = 4,
    ACTIONS(299), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(301), 1,
      anon_sym_LT_SLASH,
    ACTIONS(303), 1,
      sym_raw_text,
    STATE(76), 1,
      sym_end_tag,
  [1735] = 4,
    ACTIONS(299), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(301), 1,
      anon_sym_LT_SLASH,
    ACTIONS(305), 1,
      sym_raw_text,
    STATE(74), 1,
      sym_end_tag,
  [1748] = 3,
    ACTIONS(307), 1,
      anon_sym_GT,
    ACTIONS(309), 1,
      sym_attribute_name,
    STATE(102), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1759] = 3,
    ACTIONS(309), 1,
      sym_attribute_name,
    ACTIONS(311), 1,
      anon_sym_GT,
    STATE(94), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1770] = 2,
    ACTIONS(315), 1,
      anon_sym_EQ,
    ACTIONS(313), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1779] = 4,
    ACTIONS(317), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(319), 1,
      anon_sym_LT_SLASH,
    ACTIONS(321), 1,
      sym_raw_text,
    STATE(47), 1,
      sym_end_tag,
  [1792] = 3,
    ACTIONS(309), 1,
      sym_attribute_name,
    ACTIONS(323), 1,
      anon_sym_GT,
    STATE(94), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1803] = 4,
    ACTIONS(317), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(319), 1,
      anon_sym_LT_SLASH,
    ACTIONS(325), 1,
      sym_raw_text,
    STATE(45), 1,
      sym_end_tag,
  [1816] = 3,
    ACTIONS(309), 1,
      sym_attribute_name,
    ACTIONS(327), 1,
      anon_sym_GT,
    STATE(99), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1827] = 2,
    ACTIONS(331), 1,
      anon_sym_LT_SLASH,
    ACTIONS(329), 2,
      sym_raw_text,
      anon_sym_LT_SLASH_GT,
  [1835] = 3,
    ACTIONS(299), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(301), 1,
      anon_sym_LT_SLASH,
    STATE(75), 1,
      sym_end_tag,
  [1845] = 3,
    ACTIONS(317), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(319), 1,
      anon_sym_LT_SLASH,
    STATE(36), 1,
      sym_end_tag,
  [1855] = 3,
    ACTIONS(317), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(319), 1,
      anon_sym_LT_SLASH,
    STATE(39), 1,
      sym_end_tag,
  [1865] = 2,
    ACTIONS(335), 1,
      anon_sym_LT_SLASH,
    ACTIONS(333), 2,
      sym_raw_text,
      anon_sym_LT_SLASH_GT,
  [1873] = 2,
    ACTIONS(339), 1,
      anon_sym_LT_SLASH,
    ACTIONS(337), 2,
      sym_raw_text,
      anon_sym_LT_SLASH_GT,
  [1881] = 3,
    ACTIONS(341), 1,
      anon_sym_GT,
    ACTIONS(343), 1,
      sym__end_tag_name,
    ACTIONS(345), 1,
      sym_erroneous_end_tag_name,
  [1891] = 3,
    ACTIONS(282), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(284), 1,
      anon_sym_LT_SLASH,
    STATE(51), 1,
      sym_end_tag,
  [1901] = 2,
    ACTIONS(347), 1,
      anon_sym_EQ,
    ACTIONS(313), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1909] = 3,
    ACTIONS(282), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(284), 1,
      anon_sym_LT_SLASH,
    STATE(50), 1,
      sym_end_tag,
  [1919] = 1,
    ACTIONS(349), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1925] = 3,
    ACTIONS(345), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(351), 1,
      anon_sym_GT,
    ACTIONS(353), 1,
      sym__end_tag_name,
  [1935] = 3,
    ACTIONS(299), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(301), 1,
      anon_sym_LT_SLASH,
    STATE(71), 1,
      sym_end_tag,
  [1945] = 1,
    ACTIONS(355), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1951] = 2,
    ACTIONS(359), 1,
      anon_sym_LT_SLASH,
    ACTIONS(357), 2,
      sym_raw_text,
      anon_sym_LT_SLASH_GT,
  [1959] = 1,
    ACTIONS(361), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1965] = 3,
    ACTIONS(345), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(363), 1,
      anon_sym_GT,
    ACTIONS(365), 1,
      sym__end_tag_name,
  [1975] = 2,
    ACTIONS(367), 1,
      anon_sym_SQUOTE,
    ACTIONS(369), 1,
      aux_sym_quoted_attribute_value_token1,
  [1982] = 2,
    ACTIONS(371), 1,
      anon_sym_SQUOTE,
    ACTIONS(373), 1,
      aux_sym_quoted_attribute_value_token1,
  [1989] = 2,
    ACTIONS(341), 1,
      anon_sym_GT,
    ACTIONS(343), 1,
      sym__end_tag_name,
  [1996] = 2,
    ACTIONS(363), 1,
      anon_sym_GT,
    ACTIONS(365), 1,
      sym__end_tag_name,
  [2003] = 2,
    ACTIONS(351), 1,
      anon_sym_GT,
    ACTIONS(353), 1,
      sym__end_tag_name,
  [2010] = 1,
    ACTIONS(355), 2,
      anon_sym_GT,
      sym_attribute_name,
  [2015] = 1,
    ACTIONS(361), 2,
      anon_sym_GT,
      sym_attribute_name,
  [2020] = 1,
    ACTIONS(349), 2,
      anon_sym_GT,
      sym_attribute_name,
  [2025] = 2,
    ACTIONS(371), 1,
      anon_sym_DQUOTE,
    ACTIONS(375), 1,
      aux_sym_quoted_attribute_value_token2,
  [2032] = 2,
    ACTIONS(367), 1,
      anon_sym_DQUOTE,
    ACTIONS(377), 1,
      aux_sym_quoted_attribute_value_token2,
  [2039] = 1,
    ACTIONS(379), 1,
      anon_sym_GT,
  [2043] = 1,
    ACTIONS(381), 1,
      sym_erroneous_end_tag_name,
  [2047] = 1,
    ACTIONS(383), 1,
      anon_sym_DQUOTE,
  [2051] = 1,
    ACTIONS(385), 1,
      ts_builtin_sym_end,
  [2055] = 1,
    ACTIONS(387), 1,
      sym_erroneous_end_tag_name,
  [2059] = 1,
    ACTIONS(389), 1,
      anon_sym_GT,
  [2063] = 1,
    ACTIONS(383), 1,
      anon_sym_SQUOTE,
  [2067] = 1,
    ACTIONS(391), 1,
      anon_sym_GT,
  [2071] = 1,
    ACTIONS(393), 1,
      anon_sym_GT,
  [2075] = 1,
    ACTIONS(395), 1,
      aux_sym_doctype_token1,
  [2079] = 1,
    ACTIONS(397), 1,
      sym__doctype,
  [2083] = 1,
    ACTIONS(399), 1,
      anon_sym_GT,
  [2087] = 1,
    ACTIONS(401), 1,
      anon_sym_DQUOTE,
  [2091] = 1,
    ACTIONS(403), 1,
      anon_sym_GT,
  [2095] = 1,
    ACTIONS(405), 1,
      anon_sym_GT,
  [2099] = 1,
    ACTIONS(407), 1,
      sym__doctype,
  [2103] = 1,
    ACTIONS(409), 1,
      anon_sym_GT,
  [2107] = 1,
    ACTIONS(411), 1,
      anon_sym_GT,
  [2111] = 1,
    ACTIONS(413), 1,
      aux_sym_doctype_token1,
  [2115] = 1,
    ACTIONS(345), 1,
      sym_erroneous_end_tag_name,
  [2119] = 1,
    ACTIONS(415), 1,
      aux_sym_doctype_token1,
  [2123] = 1,
    ACTIONS(417), 1,
      sym__doctype,
  [2127] = 1,
    ACTIONS(401), 1,
      anon_sym_SQUOTE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 47,
  [SMALL_STATE(4)] = 94,
  [SMALL_STATE(5)] = 141,
  [SMALL_STATE(6)] = 188,
  [SMALL_STATE(7)] = 235,
  [SMALL_STATE(8)] = 282,
  [SMALL_STATE(9)] = 326,
  [SMALL_STATE(10)] = 370,
  [SMALL_STATE(11)] = 414,
  [SMALL_STATE(12)] = 458,
  [SMALL_STATE(13)] = 502,
  [SMALL_STATE(14)] = 546,
  [SMALL_STATE(15)] = 590,
  [SMALL_STATE(16)] = 634,
  [SMALL_STATE(17)] = 678,
  [SMALL_STATE(18)] = 722,
  [SMALL_STATE(19)] = 745,
  [SMALL_STATE(20)] = 768,
  [SMALL_STATE(21)] = 791,
  [SMALL_STATE(22)] = 808,
  [SMALL_STATE(23)] = 825,
  [SMALL_STATE(24)] = 837,
  [SMALL_STATE(25)] = 849,
  [SMALL_STATE(26)] = 861,
  [SMALL_STATE(27)] = 873,
  [SMALL_STATE(28)] = 885,
  [SMALL_STATE(29)] = 897,
  [SMALL_STATE(30)] = 909,
  [SMALL_STATE(31)] = 921,
  [SMALL_STATE(32)] = 933,
  [SMALL_STATE(33)] = 945,
  [SMALL_STATE(34)] = 957,
  [SMALL_STATE(35)] = 969,
  [SMALL_STATE(36)] = 981,
  [SMALL_STATE(37)] = 993,
  [SMALL_STATE(38)] = 1005,
  [SMALL_STATE(39)] = 1017,
  [SMALL_STATE(40)] = 1029,
  [SMALL_STATE(41)] = 1041,
  [SMALL_STATE(42)] = 1053,
  [SMALL_STATE(43)] = 1065,
  [SMALL_STATE(44)] = 1077,
  [SMALL_STATE(45)] = 1089,
  [SMALL_STATE(46)] = 1101,
  [SMALL_STATE(47)] = 1113,
  [SMALL_STATE(48)] = 1125,
  [SMALL_STATE(49)] = 1137,
  [SMALL_STATE(50)] = 1149,
  [SMALL_STATE(51)] = 1161,
  [SMALL_STATE(52)] = 1173,
  [SMALL_STATE(53)] = 1185,
  [SMALL_STATE(54)] = 1197,
  [SMALL_STATE(55)] = 1209,
  [SMALL_STATE(56)] = 1221,
  [SMALL_STATE(57)] = 1233,
  [SMALL_STATE(58)] = 1245,
  [SMALL_STATE(59)] = 1257,
  [SMALL_STATE(60)] = 1269,
  [SMALL_STATE(61)] = 1281,
  [SMALL_STATE(62)] = 1293,
  [SMALL_STATE(63)] = 1305,
  [SMALL_STATE(64)] = 1317,
  [SMALL_STATE(65)] = 1329,
  [SMALL_STATE(66)] = 1341,
  [SMALL_STATE(67)] = 1353,
  [SMALL_STATE(68)] = 1365,
  [SMALL_STATE(69)] = 1377,
  [SMALL_STATE(70)] = 1389,
  [SMALL_STATE(71)] = 1401,
  [SMALL_STATE(72)] = 1413,
  [SMALL_STATE(73)] = 1425,
  [SMALL_STATE(74)] = 1437,
  [SMALL_STATE(75)] = 1449,
  [SMALL_STATE(76)] = 1461,
  [SMALL_STATE(77)] = 1473,
  [SMALL_STATE(78)] = 1485,
  [SMALL_STATE(79)] = 1497,
  [SMALL_STATE(80)] = 1509,
  [SMALL_STATE(81)] = 1521,
  [SMALL_STATE(82)] = 1535,
  [SMALL_STATE(83)] = 1549,
  [SMALL_STATE(84)] = 1561,
  [SMALL_STATE(85)] = 1575,
  [SMALL_STATE(86)] = 1589,
  [SMALL_STATE(87)] = 1603,
  [SMALL_STATE(88)] = 1617,
  [SMALL_STATE(89)] = 1631,
  [SMALL_STATE(90)] = 1645,
  [SMALL_STATE(91)] = 1659,
  [SMALL_STATE(92)] = 1672,
  [SMALL_STATE(93)] = 1685,
  [SMALL_STATE(94)] = 1698,
  [SMALL_STATE(95)] = 1709,
  [SMALL_STATE(96)] = 1722,
  [SMALL_STATE(97)] = 1735,
  [SMALL_STATE(98)] = 1748,
  [SMALL_STATE(99)] = 1759,
  [SMALL_STATE(100)] = 1770,
  [SMALL_STATE(101)] = 1779,
  [SMALL_STATE(102)] = 1792,
  [SMALL_STATE(103)] = 1803,
  [SMALL_STATE(104)] = 1816,
  [SMALL_STATE(105)] = 1827,
  [SMALL_STATE(106)] = 1835,
  [SMALL_STATE(107)] = 1845,
  [SMALL_STATE(108)] = 1855,
  [SMALL_STATE(109)] = 1865,
  [SMALL_STATE(110)] = 1873,
  [SMALL_STATE(111)] = 1881,
  [SMALL_STATE(112)] = 1891,
  [SMALL_STATE(113)] = 1901,
  [SMALL_STATE(114)] = 1909,
  [SMALL_STATE(115)] = 1919,
  [SMALL_STATE(116)] = 1925,
  [SMALL_STATE(117)] = 1935,
  [SMALL_STATE(118)] = 1945,
  [SMALL_STATE(119)] = 1951,
  [SMALL_STATE(120)] = 1959,
  [SMALL_STATE(121)] = 1965,
  [SMALL_STATE(122)] = 1975,
  [SMALL_STATE(123)] = 1982,
  [SMALL_STATE(124)] = 1989,
  [SMALL_STATE(125)] = 1996,
  [SMALL_STATE(126)] = 2003,
  [SMALL_STATE(127)] = 2010,
  [SMALL_STATE(128)] = 2015,
  [SMALL_STATE(129)] = 2020,
  [SMALL_STATE(130)] = 2025,
  [SMALL_STATE(131)] = 2032,
  [SMALL_STATE(132)] = 2039,
  [SMALL_STATE(133)] = 2043,
  [SMALL_STATE(134)] = 2047,
  [SMALL_STATE(135)] = 2051,
  [SMALL_STATE(136)] = 2055,
  [SMALL_STATE(137)] = 2059,
  [SMALL_STATE(138)] = 2063,
  [SMALL_STATE(139)] = 2067,
  [SMALL_STATE(140)] = 2071,
  [SMALL_STATE(141)] = 2075,
  [SMALL_STATE(142)] = 2079,
  [SMALL_STATE(143)] = 2083,
  [SMALL_STATE(144)] = 2087,
  [SMALL_STATE(145)] = 2091,
  [SMALL_STATE(146)] = 2095,
  [SMALL_STATE(147)] = 2099,
  [SMALL_STATE(148)] = 2103,
  [SMALL_STATE(149)] = 2107,
  [SMALL_STATE(150)] = 2111,
  [SMALL_STATE(151)] = 2115,
  [SMALL_STATE(152)] = 2119,
  [SMALL_STATE(153)] = 2123,
  [SMALL_STATE(154)] = 2127,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(147),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(136),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(142),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(121),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(153),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(133),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 1),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(142),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(9),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(19),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(62),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(151),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(13),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [107] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(153),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(12),
  [113] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(20),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(65),
  [119] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(133),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(15),
  [125] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(147),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(8),
  [131] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(18),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(25),
  [137] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(136),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(16),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [165] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_self_closing_tag, 1), REDUCE(sym_end_tag, 1),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_self_closing_tag, 1), REDUCE(sym_end_tag, 1),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 1),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 1),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_erroneous_end_tag, 3),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erroneous_end_tag, 3),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 1),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 2),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 2),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 1),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 4),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 4),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2),
  [223] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 2),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 2),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4),
  [251] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 2),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 2),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2),
  [265] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(100),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [284] = {.entry = {.count = 1, .reusable = false}}, SHIFT(126),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [294] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(113),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [301] = {.entry = {.count = 1, .reusable = false}}, SHIFT(125),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [319] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4),
  [331] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_start_tag, 4),
  [333] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3),
  [335] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_start_tag, 3),
  [337] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3),
  [339] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_start_tag, 3),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [349] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [355] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4),
  [359] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_start_tag, 4),
  [361] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [367] = {.entry = {.count = 1, .reusable = false}}, SHIFT(128),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(154),
  [371] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [385] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(152),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [401] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [409] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [411] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [413] = {.entry = {.count = 1, .reusable = true}}, SHIFT(149),
  [415] = {.entry = {.count = 1, .reusable = true}}, SHIFT(146),
  [417] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_html_external_scanner_create(void);
void tree_sitter_html_external_scanner_destroy(void *);
bool tree_sitter_html_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_html_external_scanner_serialize(void *, char *);
void tree_sitter_html_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_html(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_html_external_scanner_create,
      tree_sitter_html_external_scanner_destroy,
      tree_sitter_html_external_scanner_scan,
      tree_sitter_html_external_scanner_serialize,
      tree_sitter_html_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
