#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 141
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 9
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_LT_BANG = 1,
  aux_sym_doctype_token1 = 2,
  anon_sym_GT = 3,
  sym__doctype = 4,
  sym_comment_start_tag = 5,
  anon_sym_LT = 6,
  anon_sym_SLASH_GT = 7,
  sym_comment_end_tag = 8,
  anon_sym_LT_SLASH = 9,
  anon_sym_EQ = 10,
  sym_attribute_name = 11,
  sym_attribute_value = 12,
  anon_sym_SQUOTE = 13,
  aux_sym_quoted_attribute_value_token1 = 14,
  anon_sym_DQUOTE = 15,
  aux_sym_quoted_attribute_value_token2 = 16,
  sym__start_tag_name = 17,
  sym__script_start_tag_name = 18,
  sym__style_start_tag_name = 19,
  sym__end_tag_name = 20,
  sym_erroneous_end_tag_name = 21,
  sym__implicit_end_tag = 22,
  sym_raw_text = 23,
  sym_text = 24,
  sym_fragment = 25,
  sym_doctype = 26,
  sym__node = 27,
  sym_comment = 28,
  sym_element = 29,
  sym_script_element = 30,
  sym_style_element = 31,
  sym_start_tag = 32,
  sym_script_start_tag = 33,
  sym_style_start_tag = 34,
  sym_self_closing_tag = 35,
  sym_end_tag = 36,
  sym_erroneous_end_tag = 37,
  sym_attribute = 38,
  sym_quoted_attribute_value = 39,
  aux_sym_fragment_repeat1 = 40,
  aux_sym_start_tag_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG] = "<!",
  [aux_sym_doctype_token1] = "doctype_token1",
  [anon_sym_GT] = ">",
  [sym__doctype] = "doctype",
  [sym_comment_start_tag] = "comment_start_tag",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [sym_comment_end_tag] = "comment_end_tag",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token1] = "attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token2] = "attribute_value",
  [sym__start_tag_name] = "tag_name",
  [sym__script_start_tag_name] = "tag_name",
  [sym__style_start_tag_name] = "tag_name",
  [sym__end_tag_name] = "tag_name",
  [sym_erroneous_end_tag_name] = "erroneous_end_tag_name",
  [sym__implicit_end_tag] = "_implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_text] = "text",
  [sym_fragment] = "fragment",
  [sym_doctype] = "doctype",
  [sym__node] = "_node",
  [sym_comment] = "comment",
  [sym_element] = "element",
  [sym_script_element] = "script_element",
  [sym_style_element] = "style_element",
  [sym_start_tag] = "start_tag",
  [sym_script_start_tag] = "start_tag",
  [sym_style_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_erroneous_end_tag] = "erroneous_end_tag",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [aux_sym_fragment_repeat1] = "fragment_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [aux_sym_doctype_token1] = aux_sym_doctype_token1,
  [anon_sym_GT] = anon_sym_GT,
  [sym__doctype] = sym__doctype,
  [sym_comment_start_tag] = sym_comment_start_tag,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [sym_comment_end_tag] = sym_comment_end_tag,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token1] = sym_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token2] = sym_attribute_value,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__script_start_tag_name] = sym__start_tag_name,
  [sym__style_start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [sym__implicit_end_tag] = sym__implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_text] = sym_text,
  [sym_fragment] = sym_fragment,
  [sym_doctype] = sym_doctype,
  [sym__node] = sym__node,
  [sym_comment] = sym_comment,
  [sym_element] = sym_element,
  [sym_script_element] = sym_script_element,
  [sym_style_element] = sym_style_element,
  [sym_start_tag] = sym_start_tag,
  [sym_script_start_tag] = sym_start_tag,
  [sym_style_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_erroneous_end_tag] = sym_erroneous_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [aux_sym_fragment_repeat1] = aux_sym_fragment_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doctype_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym__doctype] = {
    .visible = true,
    .named = false,
  },
  [sym_comment_start_tag] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_comment_end_tag] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__implicit_end_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '\'') ADVANCE(30);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '<') ADVANCE(23);
      if (lookahead == '=') ADVANCE(27);
      if (lookahead == '>') ADVANCE(20);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '\'') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(29);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(22);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '=') ADVANCE(27);
      if (lookahead == '>') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '<') ADVANCE(28);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(25);
      END_STATE();
    case 9:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 11:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(14);
      END_STATE();
    case 14:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(19);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      if (lookahead == '-') ADVANCE(4);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__doctype);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_comment_start_tag);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(17);
      if (lookahead == '/') ADVANCE(26);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_comment_end_tag);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(35);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 3},
  [3] = {.lex_state = 0, .external_lex_state = 3},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 3},
  [7] = {.lex_state = 0, .external_lex_state = 3},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 0, .external_lex_state = 3},
  [13] = {.lex_state = 0, .external_lex_state = 2},
  [14] = {.lex_state = 0, .external_lex_state = 2},
  [15] = {.lex_state = 0, .external_lex_state = 2},
  [16] = {.lex_state = 0, .external_lex_state = 2},
  [17] = {.lex_state = 0, .external_lex_state = 2},
  [18] = {.lex_state = 6, .external_lex_state = 4},
  [19] = {.lex_state = 6, .external_lex_state = 4},
  [20] = {.lex_state = 6, .external_lex_state = 4},
  [21] = {.lex_state = 0, .external_lex_state = 3},
  [22] = {.lex_state = 0, .external_lex_state = 2},
  [23] = {.lex_state = 0, .external_lex_state = 3},
  [24] = {.lex_state = 0, .external_lex_state = 3},
  [25] = {.lex_state = 0, .external_lex_state = 2},
  [26] = {.lex_state = 0, .external_lex_state = 3},
  [27] = {.lex_state = 0, .external_lex_state = 3},
  [28] = {.lex_state = 0, .external_lex_state = 3},
  [29] = {.lex_state = 0, .external_lex_state = 2},
  [30] = {.lex_state = 0, .external_lex_state = 3},
  [31] = {.lex_state = 0, .external_lex_state = 2},
  [32] = {.lex_state = 0, .external_lex_state = 3},
  [33] = {.lex_state = 0, .external_lex_state = 2},
  [34] = {.lex_state = 0, .external_lex_state = 2},
  [35] = {.lex_state = 0, .external_lex_state = 2},
  [36] = {.lex_state = 0, .external_lex_state = 3},
  [37] = {.lex_state = 0, .external_lex_state = 3},
  [38] = {.lex_state = 0, .external_lex_state = 3},
  [39] = {.lex_state = 0, .external_lex_state = 2},
  [40] = {.lex_state = 0, .external_lex_state = 3},
  [41] = {.lex_state = 0, .external_lex_state = 3},
  [42] = {.lex_state = 0, .external_lex_state = 2},
  [43] = {.lex_state = 0, .external_lex_state = 3},
  [44] = {.lex_state = 0, .external_lex_state = 3},
  [45] = {.lex_state = 0, .external_lex_state = 2},
  [46] = {.lex_state = 0, .external_lex_state = 2},
  [47] = {.lex_state = 0, .external_lex_state = 2},
  [48] = {.lex_state = 0, .external_lex_state = 2},
  [49] = {.lex_state = 0, .external_lex_state = 3},
  [50] = {.lex_state = 0, .external_lex_state = 2},
  [51] = {.lex_state = 0, .external_lex_state = 3},
  [52] = {.lex_state = 0, .external_lex_state = 3},
  [53] = {.lex_state = 0, .external_lex_state = 2},
  [54] = {.lex_state = 0, .external_lex_state = 2},
  [55] = {.lex_state = 0, .external_lex_state = 2},
  [56] = {.lex_state = 0, .external_lex_state = 2},
  [57] = {.lex_state = 0, .external_lex_state = 2},
  [58] = {.lex_state = 0, .external_lex_state = 2},
  [59] = {.lex_state = 0, .external_lex_state = 2},
  [60] = {.lex_state = 0, .external_lex_state = 2},
  [61] = {.lex_state = 0, .external_lex_state = 2},
  [62] = {.lex_state = 0, .external_lex_state = 2},
  [63] = {.lex_state = 0, .external_lex_state = 2},
  [64] = {.lex_state = 0, .external_lex_state = 2},
  [65] = {.lex_state = 0, .external_lex_state = 2},
  [66] = {.lex_state = 0, .external_lex_state = 2},
  [67] = {.lex_state = 0, .external_lex_state = 2},
  [68] = {.lex_state = 0, .external_lex_state = 2},
  [69] = {.lex_state = 6, .external_lex_state = 5},
  [70] = {.lex_state = 6, .external_lex_state = 5},
  [71] = {.lex_state = 6, .external_lex_state = 5},
  [72] = {.lex_state = 6, .external_lex_state = 5},
  [73] = {.lex_state = 6, .external_lex_state = 5},
  [74] = {.lex_state = 6, .external_lex_state = 5},
  [75] = {.lex_state = 6, .external_lex_state = 5},
  [76] = {.lex_state = 6},
  [77] = {.lex_state = 6, .external_lex_state = 5},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 6},
  [80] = {.lex_state = 6},
  [81] = {.lex_state = 6},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 6},
  [84] = {.lex_state = 6},
  [85] = {.lex_state = 0, .external_lex_state = 6},
  [86] = {.lex_state = 0, .external_lex_state = 7},
  [87] = {.lex_state = 6, .external_lex_state = 5},
  [88] = {.lex_state = 0, .external_lex_state = 6},
  [89] = {.lex_state = 0, .external_lex_state = 7},
  [90] = {.lex_state = 0, .external_lex_state = 7},
  [91] = {.lex_state = 0, .external_lex_state = 7},
  [92] = {.lex_state = 6, .external_lex_state = 5},
  [93] = {.lex_state = 6, .external_lex_state = 5},
  [94] = {.lex_state = 0, .external_lex_state = 7},
  [95] = {.lex_state = 0, .external_lex_state = 7},
  [96] = {.lex_state = 6},
  [97] = {.lex_state = 0, .external_lex_state = 6},
  [98] = {.lex_state = 0, .external_lex_state = 8},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0, .external_lex_state = 8},
  [101] = {.lex_state = 6},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 6},
  [105] = {.lex_state = 3},
  [106] = {.lex_state = 0, .external_lex_state = 7},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0, .external_lex_state = 8},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0, .external_lex_state = 7},
  [111] = {.lex_state = 0, .external_lex_state = 7},
  [112] = {.lex_state = 6},
  [113] = {.lex_state = 0, .external_lex_state = 7},
  [114] = {.lex_state = 3},
  [115] = {.lex_state = 2},
  [116] = {.lex_state = 2},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 15},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 15},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 15},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0, .external_lex_state = 9},
  [136] = {.lex_state = 0, .external_lex_state = 9},
  [137] = {.lex_state = 0, .external_lex_state = 9},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
};

enum {
  ts_external_token__start_tag_name = 0,
  ts_external_token__script_start_tag_name = 1,
  ts_external_token__style_start_tag_name = 2,
  ts_external_token__end_tag_name = 3,
  ts_external_token_erroneous_end_tag_name = 4,
  ts_external_token_SLASH_GT = 5,
  ts_external_token__implicit_end_tag = 6,
  ts_external_token_raw_text = 7,
  ts_external_token_text = 8,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__script_start_tag_name] = sym__script_start_tag_name,
  [ts_external_token__style_start_tag_name] = sym__style_start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token__implicit_end_tag] = sym__implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_text] = sym_text,
};

static const bool ts_external_scanner_states[10][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_text] = true,
  },
  [2] = {
    [ts_external_token_text] = true,
  },
  [3] = {
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_text] = true,
  },
  [4] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
  },
  [5] = {
    [ts_external_token_SLASH_GT] = true,
  },
  [6] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
  },
  [7] = {
    [ts_external_token_raw_text] = true,
  },
  [8] = {
    [ts_external_token__end_tag_name] = true,
  },
  [9] = {
    [ts_external_token_erroneous_end_tag_name] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym__doctype] = ACTIONS(1),
    [sym_comment_start_tag] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [sym_comment_end_tag] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__script_start_tag_name] = ACTIONS(1),
    [sym__style_start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym_erroneous_end_tag_name] = ACTIONS(1),
    [sym__implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
  },
  [1] = {
    [sym_fragment] = STATE(133),
    [sym_doctype] = STATE(10),
    [sym__node] = STATE(10),
    [sym_comment] = STATE(10),
    [sym_element] = STATE(10),
    [sym_script_element] = STATE(10),
    [sym_style_element] = STATE(10),
    [sym_start_tag] = STATE(7),
    [sym_script_start_tag] = STATE(86),
    [sym_style_start_tag] = STATE(89),
    [sym_self_closing_tag] = STATE(39),
    [sym_erroneous_end_tag] = STATE(10),
    [aux_sym_fragment_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT_BANG] = ACTIONS(5),
    [sym_comment_start_tag] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LT_SLASH] = ACTIONS(11),
    [sym_text] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      sym_comment_start_tag,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      anon_sym_LT_SLASH,
    ACTIONS(23), 1,
      sym__implicit_end_tag,
    ACTIONS(25), 1,
      sym_text,
    STATE(2), 1,
      sym_start_tag,
    STATE(43), 1,
      sym_end_tag,
    STATE(52), 1,
      sym_self_closing_tag,
    STATE(90), 1,
      sym_style_start_tag,
    STATE(91), 1,
      sym_script_start_tag,
    STATE(6), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [44] = 12,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      sym_comment_start_tag,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    ACTIONS(29), 1,
      sym__implicit_end_tag,
    ACTIONS(31), 1,
      sym_text,
    STATE(2), 1,
      sym_start_tag,
    STATE(52), 1,
      sym_self_closing_tag,
    STATE(64), 1,
      sym_end_tag,
    STATE(90), 1,
      sym_style_start_tag,
    STATE(91), 1,
      sym_script_start_tag,
    STATE(4), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [88] = 12,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      sym_comment_start_tag,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    ACTIONS(33), 1,
      sym__implicit_end_tag,
    ACTIONS(35), 1,
      sym_text,
    STATE(2), 1,
      sym_start_tag,
    STATE(52), 1,
      sym_self_closing_tag,
    STATE(59), 1,
      sym_end_tag,
    STATE(90), 1,
      sym_style_start_tag,
    STATE(91), 1,
      sym_script_start_tag,
    STATE(12), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [132] = 12,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      sym_comment_start_tag,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(35), 1,
      sym_text,
    ACTIONS(37), 1,
      anon_sym_LT_SLASH,
    ACTIONS(39), 1,
      sym__implicit_end_tag,
    STATE(2), 1,
      sym_start_tag,
    STATE(45), 1,
      sym_end_tag,
    STATE(52), 1,
      sym_self_closing_tag,
    STATE(90), 1,
      sym_style_start_tag,
    STATE(91), 1,
      sym_script_start_tag,
    STATE(12), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [176] = 12,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      sym_comment_start_tag,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      anon_sym_LT_SLASH,
    ACTIONS(35), 1,
      sym_text,
    ACTIONS(41), 1,
      sym__implicit_end_tag,
    STATE(2), 1,
      sym_start_tag,
    STATE(30), 1,
      sym_end_tag,
    STATE(52), 1,
      sym_self_closing_tag,
    STATE(90), 1,
      sym_style_start_tag,
    STATE(91), 1,
      sym_script_start_tag,
    STATE(12), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [220] = 12,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      sym_comment_start_tag,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(37), 1,
      anon_sym_LT_SLASH,
    ACTIONS(43), 1,
      sym__implicit_end_tag,
    ACTIONS(45), 1,
      sym_text,
    STATE(2), 1,
      sym_start_tag,
    STATE(25), 1,
      sym_end_tag,
    STATE(52), 1,
      sym_self_closing_tag,
    STATE(90), 1,
      sym_style_start_tag,
    STATE(91), 1,
      sym_script_start_tag,
    STATE(5), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [264] = 11,
    ACTIONS(47), 1,
      anon_sym_LT_BANG,
    ACTIONS(50), 1,
      sym_comment_start_tag,
    ACTIONS(53), 1,
      anon_sym_LT,
    ACTIONS(56), 1,
      sym_comment_end_tag,
    ACTIONS(58), 1,
      anon_sym_LT_SLASH,
    ACTIONS(61), 1,
      sym_text,
    STATE(3), 1,
      sym_start_tag,
    STATE(61), 1,
      sym_self_closing_tag,
    STATE(94), 1,
      sym_style_start_tag,
    STATE(95), 1,
      sym_script_start_tag,
    STATE(8), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [305] = 11,
    ACTIONS(64), 1,
      anon_sym_LT_BANG,
    ACTIONS(66), 1,
      sym_comment_start_tag,
    ACTIONS(68), 1,
      anon_sym_LT,
    ACTIONS(70), 1,
      sym_comment_end_tag,
    ACTIONS(72), 1,
      anon_sym_LT_SLASH,
    ACTIONS(74), 1,
      sym_text,
    STATE(3), 1,
      sym_start_tag,
    STATE(61), 1,
      sym_self_closing_tag,
    STATE(94), 1,
      sym_style_start_tag,
    STATE(95), 1,
      sym_script_start_tag,
    STATE(8), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [346] = 11,
    ACTIONS(5), 1,
      anon_sym_LT_BANG,
    ACTIONS(7), 1,
      sym_comment_start_tag,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    ACTIONS(78), 1,
      sym_text,
    STATE(7), 1,
      sym_start_tag,
    STATE(39), 1,
      sym_self_closing_tag,
    STATE(86), 1,
      sym_script_start_tag,
    STATE(89), 1,
      sym_style_start_tag,
    STATE(17), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [387] = 11,
    ACTIONS(64), 1,
      anon_sym_LT_BANG,
    ACTIONS(66), 1,
      sym_comment_start_tag,
    ACTIONS(68), 1,
      anon_sym_LT,
    ACTIONS(72), 1,
      anon_sym_LT_SLASH,
    ACTIONS(80), 1,
      sym_comment_end_tag,
    ACTIONS(82), 1,
      sym_text,
    STATE(3), 1,
      sym_start_tag,
    STATE(61), 1,
      sym_self_closing_tag,
    STATE(94), 1,
      sym_style_start_tag,
    STATE(95), 1,
      sym_script_start_tag,
    STATE(9), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [428] = 11,
    ACTIONS(56), 1,
      sym__implicit_end_tag,
    ACTIONS(84), 1,
      anon_sym_LT_BANG,
    ACTIONS(87), 1,
      sym_comment_start_tag,
    ACTIONS(90), 1,
      anon_sym_LT,
    ACTIONS(93), 1,
      anon_sym_LT_SLASH,
    ACTIONS(96), 1,
      sym_text,
    STATE(2), 1,
      sym_start_tag,
    STATE(52), 1,
      sym_self_closing_tag,
    STATE(90), 1,
      sym_style_start_tag,
    STATE(91), 1,
      sym_script_start_tag,
    STATE(12), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [469] = 11,
    ACTIONS(64), 1,
      anon_sym_LT_BANG,
    ACTIONS(66), 1,
      sym_comment_start_tag,
    ACTIONS(68), 1,
      anon_sym_LT,
    ACTIONS(72), 1,
      anon_sym_LT_SLASH,
    ACTIONS(74), 1,
      sym_text,
    ACTIONS(99), 1,
      sym_comment_end_tag,
    STATE(3), 1,
      sym_start_tag,
    STATE(61), 1,
      sym_self_closing_tag,
    STATE(94), 1,
      sym_style_start_tag,
    STATE(95), 1,
      sym_script_start_tag,
    STATE(8), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [510] = 11,
    ACTIONS(64), 1,
      anon_sym_LT_BANG,
    ACTIONS(66), 1,
      sym_comment_start_tag,
    ACTIONS(68), 1,
      anon_sym_LT,
    ACTIONS(72), 1,
      anon_sym_LT_SLASH,
    ACTIONS(74), 1,
      sym_text,
    ACTIONS(101), 1,
      sym_comment_end_tag,
    STATE(3), 1,
      sym_start_tag,
    STATE(61), 1,
      sym_self_closing_tag,
    STATE(94), 1,
      sym_style_start_tag,
    STATE(95), 1,
      sym_script_start_tag,
    STATE(8), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [551] = 11,
    ACTIONS(64), 1,
      anon_sym_LT_BANG,
    ACTIONS(66), 1,
      sym_comment_start_tag,
    ACTIONS(68), 1,
      anon_sym_LT,
    ACTIONS(72), 1,
      anon_sym_LT_SLASH,
    ACTIONS(103), 1,
      sym_comment_end_tag,
    ACTIONS(105), 1,
      sym_text,
    STATE(3), 1,
      sym_start_tag,
    STATE(61), 1,
      sym_self_closing_tag,
    STATE(94), 1,
      sym_style_start_tag,
    STATE(95), 1,
      sym_script_start_tag,
    STATE(13), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [592] = 11,
    ACTIONS(64), 1,
      anon_sym_LT_BANG,
    ACTIONS(66), 1,
      sym_comment_start_tag,
    ACTIONS(68), 1,
      anon_sym_LT,
    ACTIONS(72), 1,
      anon_sym_LT_SLASH,
    ACTIONS(107), 1,
      sym_comment_end_tag,
    ACTIONS(109), 1,
      sym_text,
    STATE(3), 1,
      sym_start_tag,
    STATE(61), 1,
      sym_self_closing_tag,
    STATE(94), 1,
      sym_style_start_tag,
    STATE(95), 1,
      sym_script_start_tag,
    STATE(14), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [633] = 11,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(111), 1,
      anon_sym_LT_BANG,
    ACTIONS(114), 1,
      sym_comment_start_tag,
    ACTIONS(117), 1,
      anon_sym_LT,
    ACTIONS(120), 1,
      anon_sym_LT_SLASH,
    ACTIONS(123), 1,
      sym_text,
    STATE(7), 1,
      sym_start_tag,
    STATE(39), 1,
      sym_self_closing_tag,
    STATE(86), 1,
      sym_script_start_tag,
    STATE(89), 1,
      sym_style_start_tag,
    STATE(17), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [674] = 6,
    ACTIONS(126), 1,
      anon_sym_GT,
    ACTIONS(128), 1,
      sym_attribute_name,
    ACTIONS(130), 1,
      sym__start_tag_name,
    ACTIONS(132), 1,
      sym__script_start_tag_name,
    ACTIONS(134), 1,
      sym__style_start_tag_name,
    STATE(84), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [694] = 6,
    ACTIONS(126), 1,
      anon_sym_GT,
    ACTIONS(128), 1,
      sym_attribute_name,
    ACTIONS(132), 1,
      sym__script_start_tag_name,
    ACTIONS(134), 1,
      sym__style_start_tag_name,
    ACTIONS(136), 1,
      sym__start_tag_name,
    STATE(84), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [714] = 6,
    ACTIONS(126), 1,
      anon_sym_GT,
    ACTIONS(128), 1,
      sym_attribute_name,
    ACTIONS(132), 1,
      sym__script_start_tag_name,
    ACTIONS(134), 1,
      sym__style_start_tag_name,
    ACTIONS(138), 1,
      sym__start_tag_name,
    STATE(84), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [734] = 2,
    ACTIONS(140), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(142), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [745] = 2,
    ACTIONS(146), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(144), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [756] = 2,
    ACTIONS(148), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(150), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [767] = 2,
    ACTIONS(152), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(154), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [778] = 2,
    ACTIONS(158), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(156), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [789] = 2,
    ACTIONS(160), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(162), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [800] = 2,
    ACTIONS(164), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(166), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [811] = 2,
    ACTIONS(168), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(170), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [822] = 2,
    ACTIONS(174), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(172), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [833] = 2,
    ACTIONS(176), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(178), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [844] = 2,
    ACTIONS(182), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(180), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [855] = 2,
    ACTIONS(146), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(144), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [866] = 2,
    ACTIONS(186), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(184), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [877] = 2,
    ACTIONS(188), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(190), 4,
      sym_text,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [888] = 2,
    ACTIONS(188), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(190), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [899] = 2,
    ACTIONS(192), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(194), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [910] = 2,
    ACTIONS(188), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(190), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [921] = 2,
    ACTIONS(186), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(184), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [932] = 2,
    ACTIONS(198), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(196), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [943] = 2,
    ACTIONS(182), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(180), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [954] = 2,
    ACTIONS(174), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(172), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [965] = 2,
    ACTIONS(192), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(194), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [976] = 2,
    ACTIONS(158), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(156), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [987] = 2,
    ACTIONS(200), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(202), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [998] = 2,
    ACTIONS(176), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(178), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [1009] = 2,
    ACTIONS(168), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(170), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [1020] = 2,
    ACTIONS(164), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(166), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [1031] = 2,
    ACTIONS(160), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(162), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [1042] = 2,
    ACTIONS(204), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(206), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [1053] = 2,
    ACTIONS(152), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(154), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [1064] = 2,
    ACTIONS(208), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(210), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [1075] = 2,
    ACTIONS(198), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(196), 4,
      sym__implicit_end_tag,
      sym_text,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [1086] = 2,
    ACTIONS(148), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(150), 4,
      sym_text,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [1097] = 2,
    ACTIONS(152), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(154), 4,
      sym_text,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [1108] = 2,
    ACTIONS(160), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(162), 4,
      sym_text,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [1119] = 2,
    ACTIONS(148), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(150), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [1130] = 2,
    ACTIONS(164), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(166), 4,
      sym_text,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [1141] = 2,
    ACTIONS(168), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(170), 4,
      sym_text,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [1152] = 2,
    ACTIONS(176), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(178), 4,
      sym_text,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [1163] = 2,
    ACTIONS(146), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(144), 4,
      sym_text,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [1174] = 2,
    ACTIONS(198), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(196), 4,
      sym_text,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [1185] = 2,
    ACTIONS(208), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(210), 4,
      sym_text,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [1196] = 2,
    ACTIONS(192), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(194), 4,
      sym_text,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [1207] = 2,
    ACTIONS(158), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(156), 4,
      sym_text,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [1218] = 2,
    ACTIONS(174), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(172), 4,
      sym_text,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [1229] = 2,
    ACTIONS(182), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(180), 4,
      sym_text,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [1240] = 2,
    ACTIONS(208), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(210), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_comment_start_tag,
      anon_sym_LT_SLASH,
  [1251] = 2,
    ACTIONS(186), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(184), 4,
      sym_text,
      sym_comment_start_tag,
      sym_comment_end_tag,
      anon_sym_LT_SLASH,
  [1262] = 4,
    ACTIONS(212), 1,
      anon_sym_GT,
    ACTIONS(214), 1,
      anon_sym_SLASH_GT,
    ACTIONS(216), 1,
      sym_attribute_name,
    STATE(74), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1276] = 4,
    ACTIONS(212), 1,
      anon_sym_GT,
    ACTIONS(216), 1,
      sym_attribute_name,
    ACTIONS(218), 1,
      anon_sym_SLASH_GT,
    STATE(74), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1290] = 4,
    ACTIONS(216), 1,
      sym_attribute_name,
    ACTIONS(220), 1,
      anon_sym_GT,
    ACTIONS(222), 1,
      anon_sym_SLASH_GT,
    STATE(70), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1304] = 4,
    ACTIONS(216), 1,
      sym_attribute_name,
    ACTIONS(220), 1,
      anon_sym_GT,
    ACTIONS(224), 1,
      anon_sym_SLASH_GT,
    STATE(69), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1318] = 4,
    ACTIONS(212), 1,
      anon_sym_GT,
    ACTIONS(216), 1,
      sym_attribute_name,
    ACTIONS(226), 1,
      anon_sym_SLASH_GT,
    STATE(74), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1332] = 3,
    ACTIONS(230), 1,
      sym_attribute_name,
    ACTIONS(228), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(74), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1344] = 4,
    ACTIONS(216), 1,
      sym_attribute_name,
    ACTIONS(220), 1,
      anon_sym_GT,
    ACTIONS(233), 1,
      anon_sym_SLASH_GT,
    STATE(73), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1358] = 3,
    ACTIONS(128), 1,
      sym_attribute_name,
    ACTIONS(235), 1,
      anon_sym_GT,
    STATE(81), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1369] = 2,
    ACTIONS(239), 1,
      anon_sym_EQ,
    ACTIONS(237), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1378] = 4,
    ACTIONS(241), 1,
      sym_attribute_value,
    ACTIONS(243), 1,
      anon_sym_SQUOTE,
    ACTIONS(245), 1,
      anon_sym_DQUOTE,
    STATE(92), 1,
      sym_quoted_attribute_value,
  [1391] = 3,
    ACTIONS(128), 1,
      sym_attribute_name,
    ACTIONS(247), 1,
      anon_sym_GT,
    STATE(76), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1402] = 3,
    ACTIONS(128), 1,
      sym_attribute_name,
    ACTIONS(249), 1,
      anon_sym_GT,
    STATE(83), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1413] = 3,
    ACTIONS(228), 1,
      anon_sym_GT,
    ACTIONS(251), 1,
      sym_attribute_name,
    STATE(81), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1424] = 4,
    ACTIONS(254), 1,
      sym_attribute_value,
    ACTIONS(256), 1,
      anon_sym_SQUOTE,
    ACTIONS(258), 1,
      anon_sym_DQUOTE,
    STATE(104), 1,
      sym_quoted_attribute_value,
  [1437] = 3,
    ACTIONS(128), 1,
      sym_attribute_name,
    ACTIONS(260), 1,
      anon_sym_GT,
    STATE(81), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1448] = 3,
    ACTIONS(128), 1,
      sym_attribute_name,
    ACTIONS(220), 1,
      anon_sym_GT,
    STATE(81), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1459] = 3,
    ACTIONS(262), 1,
      anon_sym_GT,
    ACTIONS(264), 1,
      sym__end_tag_name,
    ACTIONS(266), 1,
      sym_erroneous_end_tag_name,
  [1469] = 3,
    ACTIONS(268), 1,
      anon_sym_LT_SLASH,
    ACTIONS(270), 1,
      sym_raw_text,
    STATE(29), 1,
      sym_end_tag,
  [1479] = 1,
    ACTIONS(272), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1485] = 3,
    ACTIONS(266), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(274), 1,
      anon_sym_GT,
    ACTIONS(276), 1,
      sym__end_tag_name,
  [1495] = 3,
    ACTIONS(268), 1,
      anon_sym_LT_SLASH,
    ACTIONS(278), 1,
      sym_raw_text,
    STATE(31), 1,
      sym_end_tag,
  [1505] = 3,
    ACTIONS(280), 1,
      anon_sym_LT_SLASH,
    ACTIONS(282), 1,
      sym_raw_text,
    STATE(40), 1,
      sym_end_tag,
  [1515] = 3,
    ACTIONS(280), 1,
      anon_sym_LT_SLASH,
    ACTIONS(284), 1,
      sym_raw_text,
    STATE(41), 1,
      sym_end_tag,
  [1525] = 1,
    ACTIONS(286), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1531] = 1,
    ACTIONS(288), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1537] = 3,
    ACTIONS(290), 1,
      anon_sym_LT_SLASH,
    ACTIONS(292), 1,
      sym_raw_text,
    STATE(66), 1,
      sym_end_tag,
  [1547] = 3,
    ACTIONS(290), 1,
      anon_sym_LT_SLASH,
    ACTIONS(294), 1,
      sym_raw_text,
    STATE(65), 1,
      sym_end_tag,
  [1557] = 2,
    ACTIONS(296), 1,
      anon_sym_EQ,
    ACTIONS(237), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1565] = 3,
    ACTIONS(266), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(298), 1,
      anon_sym_GT,
    ACTIONS(300), 1,
      sym__end_tag_name,
  [1575] = 2,
    ACTIONS(274), 1,
      anon_sym_GT,
    ACTIONS(276), 1,
      sym__end_tag_name,
  [1582] = 2,
    ACTIONS(268), 1,
      anon_sym_LT_SLASH,
    STATE(46), 1,
      sym_end_tag,
  [1589] = 2,
    ACTIONS(298), 1,
      anon_sym_GT,
    ACTIONS(300), 1,
      sym__end_tag_name,
  [1596] = 1,
    ACTIONS(272), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1601] = 2,
    ACTIONS(280), 1,
      anon_sym_LT_SLASH,
    STATE(27), 1,
      sym_end_tag,
  [1608] = 2,
    ACTIONS(280), 1,
      anon_sym_LT_SLASH,
    STATE(28), 1,
      sym_end_tag,
  [1615] = 1,
    ACTIONS(286), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1620] = 2,
    ACTIONS(302), 1,
      anon_sym_SQUOTE,
    ACTIONS(304), 1,
      aux_sym_quoted_attribute_value_token1,
  [1627] = 1,
    ACTIONS(306), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1632] = 2,
    ACTIONS(290), 1,
      anon_sym_LT_SLASH,
    STATE(58), 1,
      sym_end_tag,
  [1639] = 2,
    ACTIONS(262), 1,
      anon_sym_GT,
    ACTIONS(264), 1,
      sym__end_tag_name,
  [1646] = 2,
    ACTIONS(290), 1,
      anon_sym_LT_SLASH,
    STATE(57), 1,
      sym_end_tag,
  [1653] = 1,
    ACTIONS(308), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1658] = 1,
    ACTIONS(310), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1663] = 1,
    ACTIONS(288), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1668] = 1,
    ACTIONS(312), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1673] = 2,
    ACTIONS(314), 1,
      anon_sym_SQUOTE,
    ACTIONS(316), 1,
      aux_sym_quoted_attribute_value_token1,
  [1680] = 2,
    ACTIONS(314), 1,
      anon_sym_DQUOTE,
    ACTIONS(318), 1,
      aux_sym_quoted_attribute_value_token2,
  [1687] = 2,
    ACTIONS(302), 1,
      anon_sym_DQUOTE,
    ACTIONS(320), 1,
      aux_sym_quoted_attribute_value_token2,
  [1694] = 2,
    ACTIONS(268), 1,
      anon_sym_LT_SLASH,
    STATE(47), 1,
      sym_end_tag,
  [1701] = 1,
    ACTIONS(322), 1,
      anon_sym_GT,
  [1705] = 1,
    ACTIONS(324), 1,
      aux_sym_doctype_token1,
  [1709] = 1,
    ACTIONS(326), 1,
      anon_sym_SQUOTE,
  [1713] = 1,
    ACTIONS(328), 1,
      anon_sym_GT,
  [1717] = 1,
    ACTIONS(330), 1,
      anon_sym_GT,
  [1721] = 1,
    ACTIONS(332), 1,
      anon_sym_DQUOTE,
  [1725] = 1,
    ACTIONS(334), 1,
      anon_sym_GT,
  [1729] = 1,
    ACTIONS(336), 1,
      anon_sym_GT,
  [1733] = 1,
    ACTIONS(338), 1,
      anon_sym_GT,
  [1737] = 1,
    ACTIONS(340), 1,
      aux_sym_doctype_token1,
  [1741] = 1,
    ACTIONS(342), 1,
      sym__doctype,
  [1745] = 1,
    ACTIONS(344), 1,
      anon_sym_GT,
  [1749] = 1,
    ACTIONS(346), 1,
      aux_sym_doctype_token1,
  [1753] = 1,
    ACTIONS(332), 1,
      anon_sym_SQUOTE,
  [1757] = 1,
    ACTIONS(348), 1,
      anon_sym_GT,
  [1761] = 1,
    ACTIONS(350), 1,
      ts_builtin_sym_end,
  [1765] = 1,
    ACTIONS(352), 1,
      sym__doctype,
  [1769] = 1,
    ACTIONS(354), 1,
      sym_erroneous_end_tag_name,
  [1773] = 1,
    ACTIONS(356), 1,
      sym_erroneous_end_tag_name,
  [1777] = 1,
    ACTIONS(266), 1,
      sym_erroneous_end_tag_name,
  [1781] = 1,
    ACTIONS(358), 1,
      anon_sym_GT,
  [1785] = 1,
    ACTIONS(360), 1,
      sym__doctype,
  [1789] = 1,
    ACTIONS(326), 1,
      anon_sym_DQUOTE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 44,
  [SMALL_STATE(4)] = 88,
  [SMALL_STATE(5)] = 132,
  [SMALL_STATE(6)] = 176,
  [SMALL_STATE(7)] = 220,
  [SMALL_STATE(8)] = 264,
  [SMALL_STATE(9)] = 305,
  [SMALL_STATE(10)] = 346,
  [SMALL_STATE(11)] = 387,
  [SMALL_STATE(12)] = 428,
  [SMALL_STATE(13)] = 469,
  [SMALL_STATE(14)] = 510,
  [SMALL_STATE(15)] = 551,
  [SMALL_STATE(16)] = 592,
  [SMALL_STATE(17)] = 633,
  [SMALL_STATE(18)] = 674,
  [SMALL_STATE(19)] = 694,
  [SMALL_STATE(20)] = 714,
  [SMALL_STATE(21)] = 734,
  [SMALL_STATE(22)] = 745,
  [SMALL_STATE(23)] = 756,
  [SMALL_STATE(24)] = 767,
  [SMALL_STATE(25)] = 778,
  [SMALL_STATE(26)] = 789,
  [SMALL_STATE(27)] = 800,
  [SMALL_STATE(28)] = 811,
  [SMALL_STATE(29)] = 822,
  [SMALL_STATE(30)] = 833,
  [SMALL_STATE(31)] = 844,
  [SMALL_STATE(32)] = 855,
  [SMALL_STATE(33)] = 866,
  [SMALL_STATE(34)] = 877,
  [SMALL_STATE(35)] = 888,
  [SMALL_STATE(36)] = 899,
  [SMALL_STATE(37)] = 910,
  [SMALL_STATE(38)] = 921,
  [SMALL_STATE(39)] = 932,
  [SMALL_STATE(40)] = 943,
  [SMALL_STATE(41)] = 954,
  [SMALL_STATE(42)] = 965,
  [SMALL_STATE(43)] = 976,
  [SMALL_STATE(44)] = 987,
  [SMALL_STATE(45)] = 998,
  [SMALL_STATE(46)] = 1009,
  [SMALL_STATE(47)] = 1020,
  [SMALL_STATE(48)] = 1031,
  [SMALL_STATE(49)] = 1042,
  [SMALL_STATE(50)] = 1053,
  [SMALL_STATE(51)] = 1064,
  [SMALL_STATE(52)] = 1075,
  [SMALL_STATE(53)] = 1086,
  [SMALL_STATE(54)] = 1097,
  [SMALL_STATE(55)] = 1108,
  [SMALL_STATE(56)] = 1119,
  [SMALL_STATE(57)] = 1130,
  [SMALL_STATE(58)] = 1141,
  [SMALL_STATE(59)] = 1152,
  [SMALL_STATE(60)] = 1163,
  [SMALL_STATE(61)] = 1174,
  [SMALL_STATE(62)] = 1185,
  [SMALL_STATE(63)] = 1196,
  [SMALL_STATE(64)] = 1207,
  [SMALL_STATE(65)] = 1218,
  [SMALL_STATE(66)] = 1229,
  [SMALL_STATE(67)] = 1240,
  [SMALL_STATE(68)] = 1251,
  [SMALL_STATE(69)] = 1262,
  [SMALL_STATE(70)] = 1276,
  [SMALL_STATE(71)] = 1290,
  [SMALL_STATE(72)] = 1304,
  [SMALL_STATE(73)] = 1318,
  [SMALL_STATE(74)] = 1332,
  [SMALL_STATE(75)] = 1344,
  [SMALL_STATE(76)] = 1358,
  [SMALL_STATE(77)] = 1369,
  [SMALL_STATE(78)] = 1378,
  [SMALL_STATE(79)] = 1391,
  [SMALL_STATE(80)] = 1402,
  [SMALL_STATE(81)] = 1413,
  [SMALL_STATE(82)] = 1424,
  [SMALL_STATE(83)] = 1437,
  [SMALL_STATE(84)] = 1448,
  [SMALL_STATE(85)] = 1459,
  [SMALL_STATE(86)] = 1469,
  [SMALL_STATE(87)] = 1479,
  [SMALL_STATE(88)] = 1485,
  [SMALL_STATE(89)] = 1495,
  [SMALL_STATE(90)] = 1505,
  [SMALL_STATE(91)] = 1515,
  [SMALL_STATE(92)] = 1525,
  [SMALL_STATE(93)] = 1531,
  [SMALL_STATE(94)] = 1537,
  [SMALL_STATE(95)] = 1547,
  [SMALL_STATE(96)] = 1557,
  [SMALL_STATE(97)] = 1565,
  [SMALL_STATE(98)] = 1575,
  [SMALL_STATE(99)] = 1582,
  [SMALL_STATE(100)] = 1589,
  [SMALL_STATE(101)] = 1596,
  [SMALL_STATE(102)] = 1601,
  [SMALL_STATE(103)] = 1608,
  [SMALL_STATE(104)] = 1615,
  [SMALL_STATE(105)] = 1620,
  [SMALL_STATE(106)] = 1627,
  [SMALL_STATE(107)] = 1632,
  [SMALL_STATE(108)] = 1639,
  [SMALL_STATE(109)] = 1646,
  [SMALL_STATE(110)] = 1653,
  [SMALL_STATE(111)] = 1658,
  [SMALL_STATE(112)] = 1663,
  [SMALL_STATE(113)] = 1668,
  [SMALL_STATE(114)] = 1673,
  [SMALL_STATE(115)] = 1680,
  [SMALL_STATE(116)] = 1687,
  [SMALL_STATE(117)] = 1694,
  [SMALL_STATE(118)] = 1701,
  [SMALL_STATE(119)] = 1705,
  [SMALL_STATE(120)] = 1709,
  [SMALL_STATE(121)] = 1713,
  [SMALL_STATE(122)] = 1717,
  [SMALL_STATE(123)] = 1721,
  [SMALL_STATE(124)] = 1725,
  [SMALL_STATE(125)] = 1729,
  [SMALL_STATE(126)] = 1733,
  [SMALL_STATE(127)] = 1737,
  [SMALL_STATE(128)] = 1741,
  [SMALL_STATE(129)] = 1745,
  [SMALL_STATE(130)] = 1749,
  [SMALL_STATE(131)] = 1753,
  [SMALL_STATE(132)] = 1757,
  [SMALL_STATE(133)] = 1761,
  [SMALL_STATE(134)] = 1765,
  [SMALL_STATE(135)] = 1769,
  [SMALL_STATE(136)] = 1773,
  [SMALL_STATE(137)] = 1777,
  [SMALL_STATE(138)] = 1781,
  [SMALL_STATE(139)] = 1785,
  [SMALL_STATE(140)] = 1789,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(134),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(128),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(139),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(16),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(19),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(135),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(8),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(139),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 1),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [84] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(128),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(11),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(18),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(137),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(12),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [111] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(134),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(15),
  [117] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(20),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(136),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(17),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 2),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 2),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 4),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 4),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_erroneous_end_tag, 3),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erroneous_end_tag, 3),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 2),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 2),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2),
  [230] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(77),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [251] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(96),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [302] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4),
  [314] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [350] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_html_external_scanner_create(void);
void tree_sitter_html_external_scanner_destroy(void *);
bool tree_sitter_html_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_html_external_scanner_serialize(void *, char *);
void tree_sitter_html_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_html(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_html_external_scanner_create,
      tree_sitter_html_external_scanner_destroy,
      tree_sitter_html_external_scanner_scan,
      tree_sitter_html_external_scanner_serialize,
      tree_sitter_html_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
